#!/usr/bin/env python3
# generated by rcm-store-connect
"""rcm_contract.py — the Store tab artifact contract, as one stdlib-only helper.

Installed by the rcm-store-connect skill next to the release scripts. It does two things:

  write <kind> --out FILE [fields…]   build + validate + atomically write plan.json / upload.json /
                                      review-plan.json / review.json. Exit 1 (nothing written) when
                                      the document would violate the contract.
  validate <kind> --file FILE         exit 0 when FILE satisfies the minimum fields of
                                      docs/release-contract.md §2,
                                      exit 1 with one line per violation otherwise.
  --selftest                          proves that a poisoned document is rejected and a good
                                      one accepted.

kind is one of: plan · upload · review-plan · review. Only the minimum fields are checked;
extra fields are kept as-is. No third-party imports, no network, no project knowledge.
"""

# 규약의 정본은 rcm 의 docs/release-contract.md §2 다. 이 파일은 그 최소 필드를 "쓰기 전에 검사한다"
# 로 바꾼 것 — 스크립트가 잘못된 JSON 을 남기면 rcm 페이지가 그걸 그대로 그리기 때문에, 쓰는 쪽에서
# 막는 편이 낫다. 식별자는 영어, 주석은 한국어(집안 규칙).

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import sys
import tempfile
from typing import Any

KINDS = ("plan", "upload", "review-plan", "review")
UPLOAD_STATUSES = ("success", "partial", "rehearsal", "failed")
UPLOAD_MODES = ("rehearsal", "upload")
REVIEW_STATUSES = ("submitted", "partial", "noop", "failed")
PLAN_VERDICTS = ("ok", "blocked")
PLATFORMS = ("ios", "android")


def now_iso() -> str:
    """UTC, 초 단위, Z 접미 — 규약의 measured_at 형식."""
    return dt.datetime.now(dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


# ── 검증 ────────────────────────────────────────────────────────────────────────────────


def _is_int(v: Any) -> bool:
    return isinstance(v, int) and not isinstance(v, bool)


def _code_text_list(doc: dict, key: str, errors: list[str]) -> None:
    """blockers / warnings: [{code, text}] 의 리스트."""
    v = doc.get(key)
    if not isinstance(v, list):
        errors.append(f"{key}: must be a list")
        return
    for i, item in enumerate(v):
        if not isinstance(item, dict):
            errors.append(f"{key}[{i}]: must be an object")
            continue
        if not isinstance(item.get("code"), str) or not item["code"]:
            errors.append(f"{key}[{i}].code: must be a non-empty string")
        if not isinstance(item.get("text"), str):
            errors.append(f"{key}[{i}].text: must be a string")


def validate(kind: str, doc: Any) -> list[str]:
    """규약 §2 의 최소 필드를 검사한다. 빈 리스트면 통과."""
    if kind not in KINDS:
        return [f"unknown kind {kind!r} (expected one of {', '.join(KINDS)})"]
    if not isinstance(doc, dict):
        return ["document: must be a JSON object"]
    e: list[str] = []
    if not _is_int(doc.get("schema")):
        e.append("schema: must be an integer")

    if kind == "plan":
        if not isinstance(doc.get("build_name"), str) or not doc["build_name"]:
            e.append("build_name: must be a non-empty string")
        n = doc.get("n", "missing")
        if n == "missing":
            e.append("n: missing (use null when unknown)")
        elif n is not None and not _is_int(n):
            e.append("n: must be an integer or null")
        if not isinstance(doc.get("first_release"), bool):
            e.append("first_release: must be true or false")
        if "store" not in doc:
            e.append("store: missing (use null when the store was not read)")
        elif doc["store"] is not None and not isinstance(doc["store"], dict):
            e.append("store: must be an object or null")
        _code_text_list(doc, "blockers", e)
        _code_text_list(doc, "warnings", e)
        if n is None and isinstance(doc.get("blockers"), list) and not doc["blockers"]:
            e.append("blockers: must be non-empty when n is null")
        if not isinstance(doc.get("measured_at"), str):
            e.append("measured_at: must be a string")

    elif kind == "upload":
        n = doc.get("n", "missing")
        if n == "missing":
            e.append("n: missing (use null when unknown)")
        elif n is not None and not _is_int(n):
            e.append("n: must be an integer or null")
        if doc.get("status") not in UPLOAD_STATUSES:
            e.append(f"status: must be one of {'|'.join(UPLOAD_STATUSES)}")
        if doc.get("mode") not in UPLOAD_MODES:
            e.append(f"mode: must be one of {'|'.join(UPLOAD_MODES)}")
        if doc.get("mode") == "rehearsal" and doc.get("status") != "rehearsal":
            e.append("status: must be 'rehearsal' when mode is 'rehearsal'")
        p = doc.get("platforms")
        if not isinstance(p, list) or not all(isinstance(x, str) for x in p):
            e.append("platforms: must be a list of strings")
        if "tag" not in doc:
            e.append("tag: missing (use null before the tag exists)")
        elif doc["tag"] is not None and not isinstance(doc["tag"], str):
            e.append("tag: must be a string or null")

    elif kind == "review-plan":
        if not isinstance(doc.get("build_name"), str) or not doc["build_name"]:
            e.append("build_name: must be a non-empty string")
        n = doc.get("n", "missing")
        if n == "missing":
            e.append("n: missing (use null when unknown)")
        elif n is not None and not _is_int(n):
            e.append("n: must be an integer or null")
        if doc.get("plan_verdict") not in PLAN_VERDICTS:
            e.append(f"plan_verdict: must be one of {'|'.join(PLAN_VERDICTS)}")
        for plat in PLATFORMS:
            if not isinstance(doc.get(plat), str) or not doc[plat]:
                e.append(f"{plat}: must be a non-empty verdict word")
        if not isinstance(doc.get("observed"), dict):
            e.append("observed: must be an object")
        listing = doc.get("listing")
        if not isinstance(listing, dict):
            e.append("listing: must be an object with preview[] and diff[]")
        else:
            for key in ("preview", "diff"):
                v = listing.get(key)
                if not isinstance(v, list) or not all(isinstance(x, str) for x in v):
                    e.append(f"listing.{key}: must be a list of strings")
        if not isinstance(doc.get("measured_at"), str):
            e.append("measured_at: must be a string")

    elif kind == "review":
        if doc.get("overall_status") not in REVIEW_STATUSES:
            e.append(f"overall_status: must be one of {'|'.join(REVIEW_STATUSES)}")
        plats = doc.get("platforms")
        if not isinstance(plats, dict) or not plats:
            e.append("platforms: must be a non-empty object")
        else:
            for name, v in plats.items():
                if not isinstance(v, dict) or not isinstance(v.get("status"), str):
                    e.append(f"platforms.{name}: must be an object with a string 'status'")
                elif "reason" not in v:
                    e.append(f"platforms.{name}.reason: missing (use null)")
        if not isinstance(doc.get("observed"), dict):
            e.append("observed: must be an object")
        if not isinstance(doc.get("auto_release"), bool):
            e.append("auto_release: must be true or false")
        if not isinstance(doc.get("phased_release"), bool):
            e.append("phased_release: must be true or false")
    return e


# ── 쓰기 ────────────────────────────────────────────────────────────────────────────────


def write_doc(kind: str, doc: dict, out: str) -> None:
    """검증 → 임시 파일 → os.replace. 검증에 걸리면 ValueError 이고 파일은 건드리지 않는다."""
    errors = validate(kind, doc)
    if errors:
        raise ValueError("\n".join(f"{kind}: {x}" for x in errors))
    os.makedirs(os.path.dirname(os.path.abspath(out)) or ".", exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".rcm-contract-", dir=os.path.dirname(os.path.abspath(out)))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(doc, f, ensure_ascii=False, indent=2)
            f.write("\n")
        os.replace(tmp, out)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _parse_n(raw: str | None) -> int | None:
    """'null' · '' · None → None, 그 외는 정수여야 한다.

    아니면 ValueError — 오염된 입력을 거른다.
    """
    if raw is None or raw == "" or raw == "null":
        return None
    try:
        return int(raw)
    except ValueError as e:
        raise ValueError(f"n: not an integer: {raw!r}") from e


def _pairs(items: list[str] | None) -> list[dict]:
    """'CODE=text' → {code, text}."""
    out = []
    for item in items or []:
        code, _, text = item.partition("=")
        out.append({"code": code, "text": text})
    return out


def _json_arg(raw: str | None, what: str) -> Any:
    """--*-json 값: 인라인 JSON, '@file', 또는 '-'(stdin)."""
    if raw is None:
        return None
    if raw == "-":
        raw = sys.stdin.read()
    elif raw.startswith("@"):
        with open(raw[1:], encoding="utf-8") as f:
            raw = f.read()
    try:
        return json.loads(raw)
    except ValueError as e:
        raise ValueError(f"{what}: not valid JSON: {e}") from e


def write_plan(
    out: str,
    build_name: str,
    n: int | None,
    first_release: bool = False,
    store: dict | None = None,
    blockers: list[dict] | None = None,
    warnings: list[dict] | None = None,
    extra: dict | None = None,
) -> dict:
    doc = {
        "schema": 1,
        "build_name": build_name,
        "n": n,
        "first_release": first_release,
        "store": store,
        "blockers": list(blockers or []),
        "warnings": list(warnings or []),
        "measured_at": now_iso(),
    }
    doc.update(extra or {})
    write_doc("plan", doc, out)
    return doc


def write_upload(
    out: str,
    n: int | None,
    status: str,
    mode: str,
    platforms: list[str],
    tag: str | None = None,
    extra: dict | None = None,
) -> dict:
    doc = {
        "schema": 1,
        "n": n,
        "status": status,
        "mode": mode,
        "platforms": list(platforms),
        "tag": tag,
    }
    doc.update(extra or {})
    write_doc("upload", doc, out)
    return doc


def write_review_plan(
    out: str,
    build_name: str,
    n: int | None,
    plan_verdict: str,
    ios: str,
    android: str,
    observed: dict | None = None,
    preview: list[str] | None = None,
    diff: list[str] | None = None,
    extra: dict | None = None,
) -> dict:
    doc = {
        "schema": 2,
        "build_name": build_name,
        "n": n,
        "plan_verdict": plan_verdict,
        "ios": ios,
        "android": android,
        "observed": dict(observed or {}),
        "listing": {"preview": list(preview or []), "diff": list(diff or [])},
        "measured_at": now_iso(),
    }
    doc.update(extra or {})
    write_doc("review-plan", doc, out)
    return doc


def write_review(
    out: str,
    overall_status: str,
    platforms: dict[str, dict],
    observed: dict | None = None,
    auto_release: bool = False,
    phased_release: bool = True,
    extra: dict | None = None,
) -> dict:
    doc = {
        "schema": 2,
        "overall_status": overall_status,
        "platforms": {k: dict(v) for k, v in platforms.items()},
        "observed": dict(observed or {}),
        "auto_release": auto_release,
        "phased_release": phased_release,
    }
    doc.update(extra or {})
    write_doc("review", doc, out)
    return doc


# ── CLI ─────────────────────────────────────────────────────────────────────────────────


def _bool(raw: str) -> bool:
    if raw in ("1", "true", "yes"):
        return True
    if raw in ("0", "false", "no"):
        return False
    raise argparse.ArgumentTypeError(f"expected 1|0, got {raw!r}")


def _platform_status(items: list[str] | None) -> dict[str, dict]:
    """'ios=submitted' · 'android=skipped:<reason>' → {name: {status, reason}}."""
    out: dict[str, dict] = {}
    for item in items or []:
        name, _, rest = item.partition("=")
        status, _, reason = rest.partition(":")
        out[name] = {"status": status, "reason": reason or None}
    return out


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="rcm_contract.py", description=__doc__.split("\n\n")[0])
    p.add_argument("--selftest", action="store_true", help="prove poisoned documents are rejected")
    sub = p.add_subparsers(dest="command")

    v = sub.add_parser("validate", help="exit 1 when FILE violates the contract")
    v.add_argument("kind", choices=KINDS)
    v.add_argument("--file", required=True)

    w = sub.add_parser("write", help="build, validate and write one artifact")
    ws = w.add_subparsers(dest="kind", required=True)

    a = ws.add_parser("plan")
    a.add_argument("--out", required=True)
    a.add_argument("--build-name", required=True)
    a.add_argument("--n", default="null", help="integer or 'null'")
    a.add_argument("--first-release", type=_bool, default=False)
    a.add_argument("--store-json", help="JSON object, @file or - (stdin); omit for null")
    a.add_argument("--blocker", action="append", metavar="CODE=text")
    a.add_argument("--warning", action="append", metavar="CODE=text")
    a.add_argument("--extra-json", help="JSON object merged on top (kept raw by rcm)")

    b = ws.add_parser("upload")
    b.add_argument("--out", required=True)
    b.add_argument("--n", default="null")
    b.add_argument("--status", required=True)
    b.add_argument("--mode", required=True)
    b.add_argument("--platform", action="append", default=[], help="repeat per platform uploaded")
    b.add_argument("--tag", default=None)
    b.add_argument("--extra-json")

    c = ws.add_parser("review-plan")
    c.add_argument("--out", required=True)
    c.add_argument("--build-name", required=True)
    c.add_argument("--n", default="null")
    c.add_argument("--plan-verdict", required=True)
    c.add_argument("--ios", required=True, help="verdict word, e.g. ready · not_requested")
    c.add_argument("--android", required=True)
    c.add_argument("--observed-json")
    c.add_argument("--preview", action="append", metavar="LINE")
    c.add_argument("--diff", action="append", metavar="LINE")
    c.add_argument("--extra-json")

    d = ws.add_parser("review")
    d.add_argument("--out", required=True)
    d.add_argument("--overall-status", required=True)
    d.add_argument("--platform-status", action="append", metavar="NAME=status[:reason]")
    d.add_argument("--observed-json")
    d.add_argument("--auto-release", type=_bool, default=False)
    d.add_argument("--phased-release", type=_bool, default=True)
    d.add_argument("--extra-json")
    return p


def cmd_validate(args: argparse.Namespace) -> int:
    try:
        with open(args.file, encoding="utf-8") as f:
            doc = json.load(f)
    except (OSError, ValueError) as e:
        print(f"{args.kind}: cannot read {args.file}: {e}", file=sys.stderr)
        return 1
    errors = validate(args.kind, doc)
    for x in errors:
        print(f"{args.kind}: {x}", file=sys.stderr)
    if errors:
        return 1
    print(f"{args.kind}: ok ({args.file})")
    return 0


def cmd_write(args: argparse.Namespace) -> int:
    try:
        extra = _json_arg(getattr(args, "extra_json", None), "--extra-json")
        if args.kind == "plan":
            doc = write_plan(
                args.out,
                args.build_name,
                _parse_n(args.n),
                args.first_release,
                _json_arg(args.store_json, "--store-json"),
                _pairs(args.blocker),
                _pairs(args.warning),
                extra,
            )
        elif args.kind == "upload":
            doc = write_upload(
                args.out, _parse_n(args.n), args.status, args.mode, args.platform, args.tag, extra
            )
        elif args.kind == "review-plan":
            doc = write_review_plan(
                args.out,
                args.build_name,
                _parse_n(args.n),
                args.plan_verdict,
                args.ios,
                args.android,
                _json_arg(args.observed_json, "--observed-json"),
                args.preview,
                args.diff,
                extra,
            )
        else:
            doc = write_review(
                args.out,
                args.overall_status,
                _platform_status(args.platform_status),
                _json_arg(args.observed_json, "--observed-json"),
                args.auto_release,
                args.phased_release,
                extra,
            )
    except ValueError as e:
        print(f"contract violation — nothing written to {args.out}\n{e}", file=sys.stderr)
        return 1
    keys = ", ".join(
        f"{k}={doc[k]!r}" for k in ("n", "status", "plan_verdict", "overall_status") if k in doc
    )
    print(f"  {os.path.basename(args.out)} -> {args.out}  {keys}")
    return 0


# ── selftest ────────────────────────────────────────────────────────────────────────────


def selftest() -> int:
    """좋은 문서 넷은 통과, 오염된 문서는 각각 거부.

    거부 이유가 해당 필드를 이름으로 가리켜야 한다.
    """
    good = {
        "plan": {
            "schema": 1,
            "build_name": "1.0.1",
            "n": 181,
            "first_release": False,
            "store": None,
            "blockers": [],
            "warnings": [],
            "measured_at": now_iso(),
        },
        "upload": {
            "schema": 1,
            "n": 181,
            "status": "rehearsal",
            "mode": "rehearsal",
            "platforms": [],
            "tag": None,
        },
        "review-plan": {
            "schema": 2,
            "build_name": "1.0.1",
            "n": 181,
            "plan_verdict": "ok",
            "ios": "ready",
            "android": "ready",
            "observed": {},
            "listing": {"preview": [], "diff": []},
            "measured_at": now_iso(),
        },
        "review": {
            "schema": 2,
            "overall_status": "noop",
            "platforms": {"ios": {"status": "skipped", "reason": "x"}},
            "observed": {},
            "auto_release": False,
            "phased_release": True,
        },
    }
    # (kind, 오염, 거부 메시지에 있어야 하는 필드 이름)
    poison = [
        ("plan", {"n": "181"}, "n"),  # 문자열 숫자 — 페이지가 비교를 못 한다
        ("plan", {"n": None, "blockers": []}, "blockers"),  # 이유 없는 null
        ("plan", {"first_release": "no"}, "first_release"),
        ("plan", {"blockers": [{"code": "B-X"}]}, "text"),
        ("upload", {"status": "done"}, "status"),
        ("upload", {"mode": "rehearsal", "status": "success"}, "rehearsal"),  # 리허설이 성공을 주장
        ("upload", {"platforms": "ios"}, "platforms"),
        ("review-plan", {"plan_verdict": "maybe"}, "plan_verdict"),
        ("review-plan", {"listing": {"preview": "x", "diff": []}}, "listing.preview"),
        ("review-plan", {"android": ""}, "android"),
        ("review", {"overall_status": "released"}, "overall_status"),
        ("review", {"auto_release": "false"}, "auto_release"),
        ("review", {"platforms": {}}, "platforms"),
    ]
    fails = 0
    for kind, doc in good.items():
        errs = validate(kind, doc)
        if errs:
            fails += 1
            print(f"FAIL good {kind}: {errs}")
    for kind, patch, field in poison:
        doc = dict(good[kind])
        doc.update(patch)
        errs = validate(kind, doc)
        if not errs or not any(field in x for x in errs):
            fails += 1
            print(f"FAIL poison {kind} {patch}: expected a complaint about {field!r}, got {errs}")
    for kind in KINDS:  # 누락 필드는 전부 이름으로 불린다
        errs = validate(kind, {"schema": 1})
        if len(errs) < 3:
            fails += 1
            print(f"FAIL missing {kind}: too few complaints: {errs}")
    # write_doc 은 오염을 만나면 파일을 건드리지 않는다
    with tempfile.TemporaryDirectory() as d:
        out = os.path.join(d, "plan.json")
        try:
            write_plan(out, "1.0.1", None, blockers=[])
            fails += 1
            print("FAIL write_plan accepted n=null with no blockers")
        except ValueError:
            pass
        if os.path.exists(out):
            fails += 1
            print("FAIL write_plan wrote a rejected document")
        write_plan(out, "1.0.1", None, blockers=[{"code": "B-TODO", "text": "stub"}])
        with open(out, encoding="utf-8") as f:
            if json.load(f)["n"] is not None:
                fails += 1
                print("FAIL write_plan changed n")
        try:
            _parse_n("18l")
            fails += 1
            print("FAIL _parse_n accepted '18l'")
        except ValueError:
            pass
    if fails:
        print(f"rcm_contract selftest FAIL ({fails})")
        return 1
    print(
        f"rcm_contract selftest ok — {len(good)} good accepted · {len(poison)} poisoned rejected · "
        "rejected documents are never written"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    p = build_parser()
    args = p.parse_args(argv)
    if args.selftest:
        return selftest()
    if args.command == "validate":
        return cmd_validate(args)
    if args.command == "write":
        return cmd_write(args)
    p.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
