#!/usr/bin/env python3
# generated by rcm-store-connect
"""rcm_candidate.py — merge this project's rcm files into a candidate server.toml and check it.

Installed by rcm-store-connect to scripts/rcm/rcm_candidate.py; the other rcm-*-connect skills
reuse it. It never edits the live server.toml: it writes a merged copy and (with --check) runs
`rcm check` on that copy.

  python3 scripts/rcm/rcm_candidate.py --server <server.toml> --repo <name>
      [--presets scripts/rcm/presets.release.toml] [--profile scripts/rcm/profile.release.toml]
      [--out <path>] [--url <git url>] [--check]
  python3 scripts/rcm/rcm_candidate.py --selftest

Defaults come from the header of docs/rcm-connect.md when it exists (`repo:`, `server_toml:`,
`presets_file:` lines); flags win. A missing --presets / --profile file is one error line, exit 2.

What the merge does, on the TOML text (comments and order are kept):
  * the profile file (the whole `[repos.<name>.release]` block, sub-tables included) is inserted
    right after the `[[repos]]` entry whose name is <name>; an existing `[repos.<name>.release…]`
    block is replaced. No entry for <name> -> one is created with `url` from --url or
    `git remote get-url origin`.
  * every `[[presets]]` of the presets file is appended; a preset of the same name already in the
    server file is removed first (with its `[presets.env]` / `[[presets.inputs]]` sub-tables).
With --check: `rcm check --config <candidate> --server http://127.0.0.1:9 --token none` runs
(`rcm` from $RCM or PATH — use the binary the server runs; its path and version are printed).
Rows that only fail because of the dummy server (`server`, `client`, `token`, and a `presets` row
that cannot reach it) are hidden; `server config` is always shown. Exit 1 when any shown row is
FAIL or when no `release <name>` row appears at all, else 0.
stdlib only.
"""

# 한 파일 = 한 블록 열. `[`, `[[` 로 시작하는 줄이 헤더다. 텍스트 수준에서 자르고 붙여야
# 주석과 순서가 살아남는다 — tomllib 는 읽기 전용이고, 읽었다 다시 쓰면 오너의 주석이 다 날아간다.

from __future__ import annotations

import argparse
import contextlib
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile

_HEADER = re.compile(r"^\s*(\[\[?)\s*([^\]]+?)\s*\]\]?\s*(?:#.*)?$")
_NAME = re.compile(r'^\s*name\s*=\s*"([^"]*)"', re.M)


def split_blocks(text: str) -> list[tuple[str, str]]:
    """(header key, block text) 의 열. 첫 원소는 헤더 없는 서문(key '')."""
    blocks: list[tuple[str, str]] = []
    key, buf = "", []
    for line in text.splitlines(keepends=True):
        m = _HEADER.match(line)
        if m and not line.lstrip().startswith("#"):
            blocks.append((key, "".join(buf)))
            key, buf = m.group(2).strip(), [line]
        else:
            buf.append(line)
    blocks.append((key, "".join(buf)))
    return blocks


def _is_array_header(block: str) -> bool:
    return block.lstrip().startswith("[[")


def block_name(block: str) -> str | None:
    m = _NAME.search(block)
    return m.group(1) if m else None


def _groups(blocks: list[tuple[str, str]], root: str) -> list[list[int]]:
    """`[[<root>]]` 하나와 그 뒤에 붙은 `<root>.…` 하위 표들의 인덱스 묶음."""
    out: list[list[int]] = []
    i = 0
    while i < len(blocks):
        key, block = blocks[i]
        if key == root and _is_array_header(block):
            grp = [i]
            j = i + 1
            while j < len(blocks) and blocks[j][0].startswith(root + "."):
                grp.append(j)
                j += 1
            out.append(grp)
            i = j
        else:
            i += 1
    return out


def merge(
    server_text: str, repo: str, profile_text: str | None, presets_text: str | None, url: str | None
) -> str:
    """머지된 server.toml 본문. url 은 저장소 항목을 새로 만들 때만 쓴다."""
    blocks = split_blocks(server_text)

    if presets_text is not None:
        if server_text.strip():
            # 대상 파일이 이미 있으면 들어오는 텍스트의 서문(주석 · 마커)은 버린다.
            # 오너 파일 한가운데 `# generated by rcm-store-connect` 가 박히면
            # 다음 실행의 Step 1 이 그 파일을 스킬 것으로 본다.
            presets_text = strip_preamble(presets_text)
        names = [block_name(g[0][1]) for g in _incoming_groups(presets_text)]
        dupes = sorted({n for n in names if n and names.count(n) > 1})
        if dupes:
            raise SystemExit(f"duplicate preset name(s) in the presets file: {', '.join(dupes)}")
        incoming = set(names)
        incoming.discard(None)
        drop: set[int] = set()
        for grp in _groups(blocks, "presets"):
            if block_name(blocks[grp[0]][1]) in incoming:
                drop.update(grp)
        blocks = [b for i, b in enumerate(blocks) if i not in drop]

    if profile_text is not None:
        target = None
        for grp in _groups(blocks, "repos"):
            if block_name(blocks[grp[0]][1]) == repo:
                target = grp
                break
        if target is None:
            if not url:
                raise SystemExit(
                    f'no [[repos]] entry named "{repo}" in the server file and no url to '
                    "create one "
                    "(pass --url or run inside a git checkout with an origin remote)"
                )
            entry = f'\n[[repos]]\nname = "{repo}"\nurl = "{url}"\n'
            blocks.append(("repos", entry))
            target = [len(blocks) - 1]
        prefix = f"repos.{repo}.release"
        keep = [
            i
            for i in target
            if not (blocks[i][0] == prefix or blocks[i][0].startswith(prefix + "."))
        ]
        last = keep[-1]
        head = [b for i, b in enumerate(blocks[: last + 1]) if i not in set(target) - set(keep)]
        tail = [
            b
            for i, b in enumerate(blocks[last + 1 :], start=last + 1)
            if i not in set(target) - set(keep)
        ]
        blocks = head + [(prefix, _pad(profile_text))] + tail

    out = "".join(b for _, b in blocks)
    if presets_text is not None:
        out = out.rstrip("\n") + "\n\n" + presets_text.strip("\n") + "\n"
    return out


def strip_preamble(text: str) -> str:
    """첫 `[[presets]]` 헤더 앞의 것을 전부 버린다."""
    blocks = split_blocks(text)
    for i, (key, block) in enumerate(blocks):
        if key == "presets" and _is_array_header(block):
            return "".join(b for _, b in blocks[i:])
    return text


def _incoming_groups(presets_text: str) -> list[list[tuple[str, str]]]:
    blocks = split_blocks(presets_text)
    return [[blocks[i] for i in grp] for grp in _groups(blocks, "presets")]


def _pad(text: str) -> str:
    return "\n" + text.strip("\n") + "\n\n"


def origin_url(cwd: str | None = None) -> str | None:
    try:
        r = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            capture_output=True,
            text=True,
            cwd=cwd,
            check=False,
        )
    except OSError:
        return None
    return r.stdout.strip() or None


def _validate(text: str) -> None:
    """tomllib 가 있으면(3.11+) 결과가 파싱되는지 본다. 없으면 건너뛴다."""
    try:
        import tomllib
    except ImportError:
        return
    tomllib.loads(text)


HIDDEN_ROWS = ("server", "client", "token")


def classify_rows(output: str, repo: str) -> tuple[list[str], int, bool]:
    """(보여줄 줄, FAIL 수, `release <repo>` 행을 봤는가).

    가짜 서버 때문에 실패하는 행만 숨긴다: `server` · `client` · `token`, 그리고 서버에 못 닿았다는
    `presets`. `server config` 는 항상 보인다 — 중복 프리셋 · choices 밖의 기본값이 거기서 나온다.
    """
    shown: list[str] = []
    bad = 0
    release_seen = False
    for line in output.splitlines():
        cols = line.split(None, 2)
        if len(cols) < 2:
            continue
        state, row, detail = cols[0], cols[1], cols[2] if len(cols) > 2 else ""
        if row in HIDDEN_ROWS and not detail.startswith("config"):
            continue
        if "127.0.0.1:9" in line or "cannot reach" in line:
            continue
        if row == "release" and detail.split(None, 1)[:1] == [repo]:
            release_seen = True
        if state == "FAIL":
            bad += 1
        shown.append(line)
    return shown, bad, release_seen


def rcm_binary() -> str:
    """$RCM 이 있으면 그것, 없으면 PATH 의 rcm — 서버가 쓰는 바로 그 바이너리여야 한다."""
    return os.environ.get("RCM") or shutil.which("rcm") or "rcm"


def run_check(candidate: str, repo: str) -> int:
    rcm = rcm_binary()
    try:
        ver = subprocess.run([rcm, "--version"], capture_output=True, text=True, check=False)
        print(f"rcm binary: {rcm} ({(ver.stdout or ver.stderr).strip() or 'version unknown'})")
        argv = [rcm, "check", "--config", candidate, "--server", "http://127.0.0.1:9"]
        r = subprocess.run(argv + ["--token", "none"], capture_output=True, text=True, check=False)
    except OSError as e:
        print(f"cannot run {rcm}: {e} (set RCM=<path to the server's rcm>)", file=sys.stderr)
        return 1
    shown, bad, release_seen = classify_rows(r.stdout + r.stderr, repo)
    for line in shown:
        print(line)
    verdict = f"{bad} FAIL row(s)" + ("" if release_seen else f" · no 'release {repo}' row")
    print(f"rcm check exit {r.returncode}; {verdict} (server/client/token rows hidden)")
    return 1 if bad or not release_seen else 0


# ── selftest ────────────────────────────────────────────────────────────────────────────────────


def selftest() -> int:
    server = (
        '[server]\nport = 8787\n\n# [[repos]]\n# name = "commented"\n\n'
        '[[repos]]\nname = "other"\nurl = "x"\n\n'
        '[[repos]]\nname = "app"   # the one\nurl = "y"\n\n'
        '[repos.app.release]\ndefault_branch = "old"\n\n'
        '[[repos.app.release.secrets]]\nname = "OLD"\n\n'
        '[[repos]]\nname = "third"\nurl = "z"\n\n'
        '[[presets]]\nname = "release-plan"\nargv = ["old"]\n'
        '[[presets.inputs]]\nname = "build_name"\n\n'
        '[[presets]]\nname = "gate"\nargv = ["gate"]\n[presets.env]\nCI = "1"\n'
    )
    profile = (
        '[repos.app.release]\ndefault_branch = "main"\n\n'
        '[repos.app.release.presets]\nplan = "release-plan"\n'
    )
    presets = (
        '[[presets]]\nname = "release-plan"\nargv = ["new"]\n'
        '[[presets.inputs]]\nname = "build_name"\n'
    )
    fails = 0

    def expect(cond: bool, what: str) -> None:
        nonlocal fails
        print(("  ok  " if cond else "FAIL ") + what)
        if not cond:
            fails += 1

    out = merge(server, "app", profile, presets, None)
    _validate(out)
    keys = [k for k, _ in split_blocks(out)]
    i_app = next(
        i for i, (k, b) in enumerate(split_blocks(out)) if k == "repos" and block_name(b) == "app"
    )
    expect(
        keys[i_app + 1] == "repos.app.release" and keys[i_app + 2] == "repos.app.release.presets",
        "profile inserted right after the app entry",
    )
    expect(
        keys[i_app + 3] == "repos" and block_name(split_blocks(out)[i_app + 3][1]) == "third",
        "next entry still follows; old release block and its secrets replaced",
    )
    expect(
        'name = "OLD"' not in out and 'default_branch = "old"' not in out,
        "old release sub-tables dropped",
    )
    expect(
        out.count('name = "release-plan"') == 1 and '["old"]' not in out and '["new"]' in out,
        "same-name preset replaced, sub-tables included",
    )
    expect(out.count('name = "gate"') == 1 and 'CI = "1"' in out, "other preset kept with its env")
    expect('# name = "commented"' in out and "# the one" in out, "comments kept")

    out2 = merge(
        server,
        "new-app",
        profile.replace("app", "new-app"),
        None,
        "git@example.invalid:o/new-app.git",
    )
    _validate(out2)
    b2 = split_blocks(out2)
    i_new = next(i for i, (k, b) in enumerate(b2) if k == "repos" and block_name(b) == "new-app")
    expect(
        'url = "git@example.invalid:o/new-app.git"' in b2[i_new][1]
        and b2[i_new + 1][0] == "repos.new-app.release",
        "missing repo entry created with the url, profile right after it",
    )
    try:
        merge(server, "nowhere", profile, None, None)
        expect(False, "missing entry without url must fail")
    except SystemExit:
        expect(True, "missing entry without url fails loudly")

    marked = "# generated by rcm-store-connect — presets\n# legend\n\n" + presets
    out3 = merge(server, "app", None, marked, None)
    expect(
        "generated by rcm-store-connect" not in out3 and '["new"]' in out3,
        "incoming preamble (marker, comments) stripped when the target exists",
    )
    expect(
        merge("", "app", None, marked, None).startswith("\n\n# generated by rcm-store-connect")
        or merge("", "app", None, marked, None).lstrip().startswith("# generated"),
        "preamble kept for a new (empty) target",
    )
    try:
        merge(server, "app", None, presets + "\n" + presets, None)
        expect(False, "duplicate preset inside the presets file must fail")
    except SystemExit:
        expect(True, "duplicate preset inside the presets file fails loudly")

    canned = (
        "ok   python        3.11\n"
        "FAIL  server        cannot reach http://127.0.0.1:9\n"
        "FAIL  token         no token\n"
        "FAIL  presets       cannot reach http://127.0.0.1:9: refused\n"
        "ok   git           /usr/bin/git\n"
    )
    shown, bad, seen = classify_rows(
        canned + "FAIL  server config /x/server.toml: duplicate preset name 'gate'\n", "app"
    )
    expect(
        bad == 1 and not seen and any(x.startswith("FAIL  server config") for x in shown),
        "FAIL server config is shown and counted; server/token/presets rows hidden",
    )
    shown, bad, seen = classify_rows(canned + "warn  release app   plan=release-plan\n", "app")
    expect(bad == 0 and seen and len(shown) == 3, "release row seen, dummy-server rows hidden")
    shown, bad, seen = classify_rows(canned + "ok   server config /x\n", "app")
    expect(bad == 0 and not seen, "no release row -> not seen (run_check exits 1)")
    shown, bad, seen = classify_rows(canned + "warn  release other plan=x\n", "app")
    expect(not seen, "release row of another repo does not count")

    with tempfile.TemporaryDirectory() as d:
        p = os.path.join(d, "server.toml")
        with open(p, "w", encoding="utf-8") as f:
            f.write(server)
        out_path = os.path.join(d, "c.toml")
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            rc = main(
                [
                    "--server",
                    p,
                    "--repo",
                    "app",
                    "--profile",
                    "-",
                    "--presets",
                    "-",
                    "--out",
                    out_path,
                ]
            )
            rc_missing = main(
                [
                    "--server",
                    p,
                    "--repo",
                    "app",
                    "--profile",
                    "-",
                    "--presets",
                    os.path.join(d, "nope.toml"),
                ]
            )
        expect(rc == 0 and os.path.exists(out_path), "CLI with '-' (no files) writes a plain copy")
        expect(rc_missing == 2, "missing --presets file -> exit 2, no traceback")
    if fails:
        print(f"rcm_candidate selftest FAIL ({fails})")
        return 1
    print(
        "rcm_candidate selftest ok — insertion after the right [[repos]], "
        "same-name preset replaced, missing entry created"
    )
    return 0


def connect_header(path: str = "docs/rcm-connect.md") -> dict[str, str]:
    """docs/rcm-connect.md 머리의 `key: value` 줄들(첫 절 이전까지). 없으면 빈 dict."""
    out: dict[str, str] = {}
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                if line.startswith("## "):
                    break
                m = re.match(
                    r"^(repo|platforms|server_toml|secrets_env|presets_file|tiers):\s*(.*)$", line
                )
                if m:
                    out[m.group(1)] = m.group(2).strip().strip("`")
    except OSError:
        pass
    return out


def main(argv: list[str] | None = None) -> int:
    hdr = connect_header()
    p = argparse.ArgumentParser(prog="rcm_candidate.py", description=__doc__.split("\n\n")[0])
    p.add_argument(
        "--server",
        default=hdr.get("server_toml") if hdr.get("server_toml", "skip") != "skip" else None,
        help="the server.toml to read (default: server_toml of docs/rcm-connect.md)",
    )
    p.add_argument(
        "--repo",
        default=hdr.get("repo"),
        help="[[repos]] name the profile belongs to (default: repo of docs/rcm-connect.md)",
    )
    p.add_argument(
        "--presets",
        default=hdr.get("presets_file") or "scripts/rcm/presets.release.toml",
        help="presets file to merge ('-' = none; default: presets_file of docs/rcm-connect.md)",
    )
    p.add_argument(
        "--profile",
        default="scripts/rcm/profile.release.toml",
        help="profile file to insert ('-' = none)",
    )
    p.add_argument("--out", help="where to write the candidate (default: a fresh temp dir)")
    p.add_argument("--url", help="repo url used only when the server file has no entry for --repo")
    p.add_argument("--check", action="store_true", help="run rcm check on the candidate")
    p.add_argument("--selftest", action="store_true")
    a = p.parse_args(argv)
    if a.selftest:
        return selftest()
    if not a.server or not a.repo:
        p.error("--server and --repo are required (or a docs/rcm-connect.md header that sets them)")

    def read(path: str) -> str | None:
        if path == "-":
            return None
        with open(path, encoding="utf-8") as f:
            return f.read()

    try:
        server_text = read(a.server) or ""
        profile_text, presets_text = read(a.profile), read(a.presets)
    except OSError as e:
        print(f"cannot read {e.filename}: {e.strerror}", file=sys.stderr)
        return 2
    try:
        out_text = merge(server_text, a.repo, profile_text, presets_text, a.url or origin_url())
        _validate(out_text)
    except (SystemExit, ValueError) as e:
        print(f"candidate not written: {e}", file=sys.stderr)
        return 1
    out = a.out or os.path.join(tempfile.mkdtemp(prefix="rcm-candidate-"), "server.toml")
    with open(out, "w", encoding="utf-8") as f:
        f.write(out_text)
    print(out)
    return run_check(out, a.repo) if a.check else 0


if __name__ == "__main__":
    sys.exit(main())
