#!/usr/bin/env bash
# generated by rcm-store-connect — release_review.sh: rcm role `review`: review plan (read-only) or submit for review.
#
#   Runs in the workspace rcm made from a git_ref (repository root). Inputs arrive as environment variables:
#     RCM_INPUT_BUILD_NAME=X.Y.Z                       required — the representative name of the round
#     RCM_INPUT_BUILD_NAME_ANDROID=X.Y.Z               default "" — the Android version name when the two stores
#                                                      ship DIFFERENT names (App Store 1.1.1 · Play 1.0.1). Empty:
#                                                      both get RCM_INPUT_BUILD_NAME. platform_build_name() picks
#     RCM_INPUT_CONFIRM_BUILD_NUMBER=N                 typed by a HUMAN; required for mode=submit, empty for plan
#     RCM_INPUT_MODE=plan|submit                       default plan — the preset default is plan and must stay so
#     RCM_INPUT_PLATFORM=both|ios|android              default both
#     RCM_INPUT_PLAY_MANAGED_PUBLISHING=not-checked|confirmed-on   default not-checked; rcm sends confirmed-on only
#                                                      when the human ticked the box in THIS submission
#     RCM_INPUT_LISTING=notes-only|full                default notes-only
#     RCM_INPUT_PHASED=1|0                             default 1 (phased release on)
#     RCM_INPUT_LISTING_JSON='{"ios":{…},"android":{…}}'  default "" — the copy edited in the web UI (version page).
#                                                      Not empty: written to build/.rcm-release/listing.json, handed to
#                                                      store_submit() as LISTING_FILE, and it wins over the store/ files;
#                                                      mode=plan echoes its fields in review-plan.json listing.preview
#   Secrets: the folder rcm hands over in ${{secrets_env}}. Never printed.
#
#   Writes  build/.rcm-release/review-plan.json (mode=plan) or review.json (mode=submit), HOWEVER THE RUN ENDS.
#   Exit codes (docs/release-contract.md §2):
#     0 ok · 1 failed · 2 blocked (env / usage / plan verdict blocked) · 3 confirmation mismatch
#     4 store drift (plan.json n != build under review) · 5 noop (nothing left to submit) · 6 partial
#   Markers: ::rcm::steps::3 · ::rcm::step::… · ::rcm::summary::… last.
#
#   Safety built in — keep it:
#     · mode=plan never calls store_submit(); mode=submit without a typed N exits 2 before any store call.
#     · Android is submitted only with play_managed_publishing=confirmed-on; otherwise skipped, reason
#       managed_publishing_unconfirmed, and the run is "partial" (exit 6) — never silently "submitted".
#     · observed auto_release == true turns both verdicts into unsafe_release_type, plan_verdict blocked, exit 2.
#     · review.json.auto_release is always false here. There is no release / rollout call in this file.
#
#   --selftest   shims replace the store; proves: default is plan (no submit call), submit needs the typed N,
#                mismatch -> 3, unconfirmed Android -> skipped + 6, auto_release observed -> blocked, poison -> red,
#                and each store is submitted under its own version name when the two differ.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; SELF="$HERE/$(basename "${BASH_SOURCE[0]}")"; ROOT="$(cd "$HERE/../.." && pwd)"; cd "$ROOT"

CONTRACT="${RCM_CONTRACT_PY:-$HERE/rcm_contract.py}"
WORK="${RELEASE_WORK:-$ROOT/build/.rcm-release}"
SECRETS_ENV="{{secrets_env}}"
# 안 채워진 템플릿(`{{secrets_env}}` 그대로)도 셀프테스트로 돌아야 한다 — bash 5 는 이름이
# 아닌 것의 간접 확장을 거부한다. 이름이 아니면 셀프테스트용 이름을 쓴다(채운 사본은 그대로).
case "$SECRETS_ENV" in ""|[0-9]*|*[!A-Za-z0-9_]*) SECRETS_ENV=RCM_TEMPLATE_SECRETS_DIR;; esac
SECRETS_DIR="${!SECRETS_ENV:-}"
SHIM="${RELEASE_SHIM:-}"                                 # selftest only: ok | autorelease | submitted | poison | fail
SHIM_CALLS="${RELEASE_SHIM_CALLS:-/dev/null}"
WRITTEN=0
MODE="${RCM_INPUT_MODE:-plan}"
LISTING_FILE=""                                          # $WORK/listing.json when RCM_INPUT_LISTING_JSON is not empty

usage() {
  echo "usage: RCM_INPUT_BUILD_NAME=X.Y.Z [RCM_INPUT_BUILD_NAME_ANDROID=X.Y.Z] [RCM_INPUT_MODE=plan|submit]" >&2
  echo "       [RCM_INPUT_CONFIRM_BUILD_NUMBER=N] [RCM_INPUT_PLATFORM=both|ios|android]" >&2
  echo "       [RCM_INPUT_PLAY_MANAGED_PUBLISHING=not-checked|confirmed-on] [RCM_INPUT_LISTING=notes-only|full] [RCM_INPUT_PHASED=1|0]" >&2
  echo "       [RCM_INPUT_LISTING_JSON='{…}'] release_review.sh | release_review.sh --selftest" >&2
  exit 2
}
# platform_build_name PLATFORM: the version name THAT store gets. One round may ship different names
#   to the two stores (docs/release-contract.md §2 «Two store version names»): android takes
#   RCM_INPUT_BUILD_NAME_ANDROID when it is not empty, anything else takes RCM_INPUT_BUILD_NAME.
platform_build_name() {
  if [ "$1" = android ] && [ -n "${RCM_INPUT_BUILD_NAME_ANDROID:-}" ]; then
    printf '%s\n' "$RCM_INPUT_BUILD_NAME_ANDROID"
  else
    printf '%s\n' "${RCM_INPUT_BUILD_NAME:-}"
  fi
}

# ── project hooks — the only places that talk to a store ─────────────────────────────────────────────
# store_review_observe BUILD_NAME: print ONE JSON object describing the build under review, read-only:
#   { "n": <int|null>,                       build number of the version the stores hold for BUILD_NAME
#     "ios":     {"verdict": "<word>", "state": "<raw store state|null>"},
#     "android": {"verdict": "<word>", "state": "<raw store state|null>"},
#     "auto_release": <bool> }               true when either store would release automatically after approval
#   verdict words rcm colours: ready · already_submitted · processing · <x>_unreadable · unsafe_release_type;
#   anything else shows red with the word as-is (e.g. not_requested, no_build, not_implemented).
store_review_observe() {
  if [ -n "$SHIM" ]; then shim_store_review_observe "$@"; return $?; fi
  # TODO(project): read the App Store version state (e.g. PREPARE_FOR_SUBMISSION / WAITING_FOR_REVIEW) and the
  #   Play track state with credentials from "$SECRETS_DIR"; set auto_release true when the ASC version is not
  #   MANUAL release or the Play track would publish on approval. $1 is the representative name — use
  #   "$(platform_build_name android)" for the Play side when the two stores ship different names.
  #   Delete the echo below when done.
  echo '{"n": null, "ios": {"verdict": "not_implemented", "state": null}, "android": {"verdict": "not_implemented", "state": null}, "auto_release": false}'
}
# listing_lines KIND: print the lines the page shows under listing.preview (KIND=preview) / listing.diff (KIND=diff).
#   When LISTING_FILE is set (the web-edited copy), the preview starts with its fields — that is what goes up.
listing_lines() {
  if [ "$1" = preview ] && [ -n "$LISTING_FILE" ]; then listing_file_lines "$LISTING_FILE"; fi
  if [ -n "$SHIM" ]; then echo "listing_lines $1" >>"$SHIM_CALLS"; echo "(shim) $1 line"; return 0; fi
  # TODO(project): print your store copy preview / diff vs live, one line each (release notes, what's new). Optional.
  #   With LISTING_FILE set, read the copy from that file instead of store/ (e.g. store_listing.py --listing-json).
  :
}
# store_submit PLATFORM N BUILD_NAME LISTING PHASED LISTING_FILE: submit ONE platform for review. Exit 0 = submitted.
#   Must NOT release, publish, roll out or change the release type. Runs only in mode=submit after the typed N matched.
#   BUILD_NAME is THAT platform's version name (platform_build_name), which is not always the same on both stores.
#   LISTING_FILE ('' or a JSON file) is the copy edited in the web UI — when given it wins over the store/ files.
store_submit() {
  if [ -n "$SHIM" ]; then shim_store_submit "$@"; return $?; fi
  # TODO(project): e.g. an existing fastlane lane that submits, with phased release = $5 and manual release ALWAYS
  #   (never automatic). $4 (notes-only|full) says whether to push the full listing or just release notes; $6, when
  #   not empty, is the JSON file whose fields replace the store/ copy (writing it back into store/ is allowed).
  echo "store_submit() is not implemented — fill the TODO(project) block in scripts/release/release_review.sh" >&2
  return 1
}

# ── selftest shims ───────────────────────────────────────────────────────────────────────────────────
shim_store_review_observe() {
  echo "store_review_observe $1" >>"$SHIM_CALLS"
  case "$SHIM" in
    ok|fail)     echo '{"n": 181, "ios": {"verdict": "ready", "state": "PREPARE_FOR_SUBMISSION"}, "android": {"verdict": "ready", "state": "completed"}, "auto_release": false}';;
    autorelease) echo '{"n": 181, "ios": {"verdict": "ready", "state": "PREPARE_FOR_SUBMISSION"}, "android": {"verdict": "ready", "state": "completed"}, "auto_release": true}';;
    submitted)   echo '{"n": 181, "ios": {"verdict": "already_submitted", "state": "WAITING_FOR_REVIEW"}, "android": {"verdict": "already_submitted", "state": "inProgress"}, "auto_release": false}';;
    poison)      echo '{"n": "181", "ios": {"verdict": ""}, "android": 3, "auto_release": "no"}';;
    *) echo "unknown RELEASE_SHIM=$SHIM" >&2; return 9;;
  esac
}
shim_store_submit() { echo "store_submit $1 $2 $3 $4 $5 ${6:-}" >>"$SHIM_CALLS"; [ "$SHIM" != fail ]; }

# ── contract plumbing ────────────────────────────────────────────────────────────────────────────────
step()     { echo "::rcm::step::$1"; }
step_end() { echo "::rcm::step-end::$1"; }
finish()   { echo "::rcm::summary::$1"; exit "$2"; }
# listing_file_lines FILE: the fields of the edited copy (listing_json) as `<platform>.<key>: <value>` lines —
#   what the page shows as «this is what goes up». One line per string field; images are counted.
listing_file_lines() {
  python3 - "$1" <<'PYEOF'
import json, sys
d = json.load(open(sys.argv[1], encoding="utf-8"))
for plat in ("ios", "android"):
    fields = d.get(plat) or {}
    if not isinstance(fields, dict):
        continue
    for key, value in fields.items():
        if isinstance(value, str):
            print(f"{plat}.{key}: {' '.join(value.split())}")
        elif isinstance(value, list):
            print(f"{plat}.{key}: {len(value)} file(s)")
PYEOF
}
# read_listing_json: RCM_INPUT_LISTING_JSON (the copy edited in the web UI) -> $WORK/listing.json + LISTING_FILE.
#   Empty = nothing edited, the store/ files are the copy. Not a JSON object = usage error (exit 2).
read_listing_json() {
  LISTING_FILE=""
  [ -n "${RCM_INPUT_LISTING_JSON:-}" ] || return 0
  if ! printf '%s' "$RCM_INPUT_LISTING_JSON" | python3 -c 'import json,sys; d=json.load(sys.stdin); assert isinstance(d, dict)' 2>/dev/null; then
    echo "RCM_INPUT_LISTING_JSON must be a JSON object ({\"ios\": {...}, \"android\": {...}})" >&2; usage
  fi
  printf '%s\n' "$RCM_INPUT_LISTING_JSON" >"$WORK/listing.json"; LISTING_FILE="$WORK/listing.json"
  echo "  listing_json given — $WORK/listing.json overrides the store/ copy"
}
write_review_plan() {  # $1 n · $2 plan_verdict · $3 ios word · $4 android word · $5 observed json · rest ignored
  python3 "$CONTRACT" write review-plan --out "$WORK/review-plan.json" --build-name "${RCM_INPUT_BUILD_NAME:-?}" \
    --n "$1" --plan-verdict "$2" --ios "$3" --android "$4" --observed-json "$5" \
    ${PREVIEW_ARGS[@]+"${PREVIEW_ARGS[@]}"} --extra-json "{\"exit_code\": ${EXIT_CODE:-null}}" && WRITTEN=1
}
write_review() {  # $1 overall · $2 observed json · $3 phased(1|0) · rest: NAME=status[:reason]
  local overall="$1" observed="$2" phased="$3"; shift 3
  local args=(write review --out "$WORK/review.json" --overall-status "$overall" --observed-json "$observed"
              --auto-release 0 --phased-release "$phased" --extra-json "{\"exit_code\": ${EXIT_CODE:-null}}")
  local s; for s in "$@"; do args+=(--platform-status "$s"); done
  python3 "$CONTRACT" "${args[@]}" && WRITTEN=1
}
PREVIEW_ARGS=()
on_exit() {  # 마지막 안전망 — 어떤 경로로 끝나든 결과 파일이 남는다
  local rc=$?
  [ "$WRITTEN" = 1 ] && return 0
  [ -n "${RCM_INPUT_BUILD_NAME:-}" ] || return 0
  if [ "$MODE" = submit ]; then
    EXIT_CODE=$rc write_review failed '{}' "${RCM_INPUT_PHASED:-1}" "ios=not_submitted:aborted_exit_$rc" "android=not_submitted:aborted_exit_$rc" >/dev/null 2>&1 || true
  else
    EXIT_CODE=$rc write_review_plan null blocked "aborted_exit_$rc" "aborted_exit_$rc" '{}' >/dev/null 2>&1 || true
  fi
}
trap on_exit EXIT

main() {
  local bn="${RCM_INPUT_BUILD_NAME:-}" confirm="${RCM_INPUT_CONFIRM_BUILD_NUMBER:-}" platform="${RCM_INPUT_PLATFORM:-both}"
  local managed="${RCM_INPUT_PLAY_MANAGED_PUBLISHING:-not-checked}" listing="${RCM_INPUT_LISTING:-notes-only}" phased="${RCM_INPUT_PHASED:-1}"
  local bna="${RCM_INPUT_BUILD_NAME_ANDROID:-}" shown
  local obs observed n ios android auto plan_n plats p verdict line rc overall
  local submitted=() skipped=() failed=()
  case "$MODE" in plan|submit) ;; *) echo "RCM_INPUT_MODE must be plan|submit, got '$MODE'" >&2; usage;; esac
  case "$platform" in both) plats="ios android";; ios|android) plats="$platform";; *) echo "RCM_INPUT_PLATFORM must be both|ios|android, got '$platform'" >&2; usage;; esac
  case "$managed" in not-checked|confirmed-on) ;; *) echo "RCM_INPUT_PLAY_MANAGED_PUBLISHING must be not-checked|confirmed-on, got '$managed'" >&2; usage;; esac
  case "$listing" in notes-only|full) ;; *) echo "RCM_INPUT_LISTING must be notes-only|full, got '$listing'" >&2; usage;; esac
  case "$phased" in 0|1) ;; *) echo "RCM_INPUT_PHASED must be 1|0, got '$phased'" >&2; usage;; esac
  [[ "$bn" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "RCM_INPUT_BUILD_NAME must be X.Y.Z, got '$bn'" >&2; usage; }
  # 두 스토어 이름이 다를 때만 온다 — 비어 있으면 둘 다 $bn 이다(계약 §2 「Two store version names」).
  [[ "$bna" =~ ^([0-9]+\.[0-9]+\.[0-9]+)?$ ]] || { echo "RCM_INPUT_BUILD_NAME_ANDROID must be X.Y.Z or empty, got '$bna'" >&2; usage; }
  shown="$bn"; if [ -n "$bna" ] && [ "$bna" != "$bn" ]; then shown="$bn+$bna"; fi
  if [ "$MODE" = submit ]; then
    [[ "$confirm" =~ ^[0-9]+$ ]] || { echo "mode=submit needs RCM_INPUT_CONFIRM_BUILD_NUMBER — the N a human typed" >&2; usage; }
  fi
  [ -f "$CONTRACT" ] || { echo "missing $CONTRACT — reinstall with /rcm-store-connect" >&2; exit 2; }
  mkdir -p "$WORK"
  read_listing_json
  echo "::rcm::steps::3"

  step "preflight"
  if [ -z "$SECRETS_DIR" ] || [ ! -d "$SECRETS_DIR" ]; then
    step_end fail
    if [ "$MODE" = submit ]; then EXIT_CODE=2 write_review failed '{}' "$phased" "ios=not_submitted:no_secrets" "android=not_submitted:no_secrets"
    else EXIT_CODE=2 write_review_plan null blocked secrets_unreadable secrets_unreadable '{}'; fi
    finish "BLOCKED(env) — secrets folder missing (\$$SECRETS_ENV)" 2
  fi
  step_end ok

  step "observe"
  obs="$WORK/review-observe.json"
  if ! store_review_observe "$bn" >"$obs"; then
    step_end fail
    if [ "$MODE" = submit ]; then EXIT_CODE=2 write_review failed '{}' "$phased" "ios=not_submitted:store_unreadable" "android=not_submitted:store_unreadable"
    else EXIT_CODE=2 write_review_plan null blocked store_unreadable store_unreadable '{}'; fi
    finish "blocked — store_review_observe() failed" 2
  fi
  # 관찰 JSON → 다섯 값. 형이 어긋나면(오염) 빈 값으로 두고 아래 규약 쓰기에서 거부되게 한다 — 가짜 ready 를 만들지 않는다.
  read -r n ios android auto < <(python3 - "$obs" <<'PY'
import json, sys
try:
    d = json.load(open(sys.argv[1], encoding="utf-8"))
    n = d.get("n"); ios = d.get("ios") or {}; andr = d.get("android") or {}; auto = d.get("auto_release")
    ok = (n is None or (isinstance(n, int) and not isinstance(n, bool))) and isinstance(ios, dict) and isinstance(andr, dict) \
        and isinstance(ios.get("verdict"), str) and ios["verdict"] and isinstance(andr.get("verdict"), str) and andr["verdict"] \
        and isinstance(auto, bool)
    if not ok:
        raise ValueError("shape")
    print("null" if n is None else n, ios["verdict"], andr["verdict"], "true" if auto else "false")
except Exception:
    print("poison", "", "", "")
PY
)
  observed="$(python3 -c 'import json,sys
try:
    d=json.load(open(sys.argv[1])); print(json.dumps({"ios": (d.get("ios") or {}).get("state") if isinstance(d.get("ios"), dict) else None, "android": (d.get("android") or {}).get("state") if isinstance(d.get("android"), dict) else None, "auto_release": d.get("auto_release") is True}))
except Exception: print("{}")' "$obs")"
  if [ "$n" = poison ]; then
    step_end fail
    if [ "$MODE" = submit ]; then EXIT_CODE=1 write_review failed "$observed" "$phased" "ios=not_submitted:contract_violation" "android=not_submitted:contract_violation"
    else EXIT_CODE=1 write_review_plan null blocked observe_unreadable observe_unreadable "$observed"; fi
    finish "failed — store_review_observe() output violates its contract (see log); nothing submitted" 1
  fi
  if [ "$auto" = true ]; then
    step_end fail
    if [ "$MODE" = submit ]; then EXIT_CODE=2 write_review failed "$observed" "$phased" "ios=not_submitted:unsafe_release_type" "android=not_submitted:unsafe_release_type"
    else EXIT_CODE=2 write_review_plan "$n" blocked unsafe_release_type unsafe_release_type "$observed"; fi
    finish "BLOCKED — the store would release automatically after approval (unsafe_release_type). Fix it in the console first" 2
  fi
  # 요청하지 않은 플랫폼은 그 말로 표시한다 — 색은 페이지 몫.
  [ "$platform" = ios ] && android=not_requested
  [ "$platform" = android ] && ios=not_requested
  # 드리프트: plan.json 이 있고 그 N 이 심사 대상 빌드와 어긋나면 4.
  if [ -f "$WORK/plan.json" ] && [ "$n" != null ]; then
    plan_n="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("n"))' "$WORK/plan.json" 2>/dev/null || echo None)"
    if [ "$plan_n" != None ] && [ "$plan_n" != "$n" ]; then
      step_end fail
      if [ "$MODE" = submit ]; then EXIT_CODE=4 write_review failed "$observed" "$phased" "ios=not_submitted:store_drift" "android=not_submitted:store_drift"
      else EXIT_CODE=4 write_review_plan "$n" blocked store_drift store_drift "$observed"; fi
      finish "store drift — plan said N=$plan_n, store holds N=$n for $bn. Re-run plan (exit 4)" 4
    fi
  fi
  step_end ok

  if [ "$MODE" = plan ]; then
    step "review-plan.json"
    while IFS= read -r line; do [ -n "$line" ] && PREVIEW_ARGS+=(--preview "$line"); done < <(listing_lines preview || true)
    while IFS= read -r line; do [ -n "$line" ] && PREVIEW_ARGS+=(--diff "$line"); done < <(listing_lines diff || true)
    verdict=ok
    for p in $plats; do
      eval "w=\$$p"
      [ "$w" = ready ] || verdict=blocked
    done
    EXIT_CODE=$([ "$verdict" = ok ] && echo 0 || echo 2) write_review_plan "$n" "$verdict" "$ios" "$android" "$observed"
    step_end ok
    [ "$verdict" = ok ] && finish "review plan ok — $shown N=$n ios=$ios android=$android (read-only; nothing submitted)" 0
    finish "review plan blocked — ios=$ios android=$android (review-plan.json)" 2
  fi

  # ── submit ──
  if [ "$confirm" != "$n" ]; then
    step_end fail
    EXIT_CODE=3 write_review failed "$observed" "$phased" "ios=not_submitted:confirmation_mismatch" "android=not_submitted:confirmation_mismatch"
    finish "confirmation mismatch — typed $confirm, store holds N=$n for $bn (exit 3)" 3
  fi
  step "submit"
  for p in $plats; do
    eval "w=\$$p"
    if [ "$w" = already_submitted ]; then skipped+=("$p=skipped:already_submitted"); continue; fi
    if [ "$w" != ready ]; then skipped+=("$p=skipped:$w"); continue; fi
    if [ "$p" = android ] && [ "$managed" != confirmed-on ]; then
      # 사람이 이 제출에서 «콘솔의 관리형 게시가 켜져 있다» 고 말하지 않았다 — API 로는 확인할 수 없으므로 건너뛴다.
      skipped+=("android=skipped:managed_publishing_unconfirmed"); continue
    fi
    if store_submit "$p" "$n" "$(platform_build_name "$p")" "$listing" "$phased" "$LISTING_FILE"; then submitted+=("$p=submitted"); else failed+=("$p=failed:store_submit_failed"); fi
  done
  if [ "${#submitted[@]}" = 0 ] && [ "${#failed[@]}" = 0 ]; then overall=noop; rc=5
  elif [ "${#skipped[@]}" = 0 ] && [ "${#failed[@]}" = 0 ]; then overall=submitted; rc=0
  elif [ "${#submitted[@]}" = 0 ]; then overall=failed; rc=1
  else overall=partial; rc=6; fi
  [ "$rc" = 0 ] && step_end ok || step_end fail
  step "review.json"
  EXIT_CODE=$rc write_review "$overall" "$observed" "$phased" ${submitted[@]+"${submitted[@]}"} ${skipped[@]+"${skipped[@]}"} ${failed[@]+"${failed[@]}"}
  step_end ok
  case "$overall" in
    submitted) finish "submitted for review — $shown N=$n ${submitted[*]-}. Release after approval is a human step in the console" 0;;
    noop)      finish "noop — nothing to submit (${skipped[*]-})" 5;;
    partial)   finish "partial — ${submitted[*]-} · ${skipped[*]-} ${failed[*]-} (not a success, exit 6)" 6;;
    *)         finish "failed — ${failed[*]-}" 1;;
  esac
}

# ── selftest ─────────────────────────────────────────────────────────────────────────────────────────
selftest() {
  local t rc fails=0
  t="$(mktemp -d)"; mkdir -p "$t/secrets"
  check() {  # $1 label · $2 expected rc · $3 actual · $4 file · $5 assertion ('' = skip) · $6 expected submit-call count
    if [ "$2" != "$3" ]; then echo "FAIL $1: exit $3, expected $2"; cat "$t/out"; fails=$((fails+1)); return; fi
    if [ -n "$5" ] && ! python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert $5, d" "$t/work/$4"; then
      echo "FAIL $1: $4 assertion failed: $5"; fails=$((fails+1)); return
    fi
    local calls; calls="$(grep -c '^store_submit' "$t/calls" 2>/dev/null || true)"; calls="${calls:-0}"
    if [ "$6" != "$calls" ]; then echo "FAIL $1: store_submit called $calls times, expected $6"; fails=$((fails+1)); return; fi
    echo "  ok  $1"
  }
  run() {  # $1 shim · $2 plan.json n ('' = none) · rest env
    local shim="$1" plan_n="$2"; shift 2
    rm -rf "$t/work" "$t/calls"; mkdir -p "$t/work"; rc=0
    [ -n "$plan_n" ] && python3 "$CONTRACT" write plan --out "$t/work/plan.json" --build-name 1.0.1 --n "$plan_n" >/dev/null
    env RELEASE_SHIM="$shim" RELEASE_SHIM_CALLS="$t/calls" RELEASE_WORK="$t/work" \
        "$SECRETS_ENV=$t/secrets" RCM_INPUT_BUILD_NAME=1.0.1 "$@" bash "$SELF" >"$t/out" 2>&1 || rc=$?
  }
  echo "[release_review] selftest ($SECRETS_ENV)"
  run ok "";                       check "no mode -> plan, no submit call" 0 "$rc" review-plan.json "d['plan_verdict']=='ok' and d['ios']=='ready' and d['n']==181 and d['listing']['preview']==['(shim) preview line'] and d['observed']['auto_release'] is False" 0
  run ok "" RCM_INPUT_CONFIRM_BUILD_NUMBER=;   check "plan with empty confirm (preset default) ok" 0 "$rc" review-plan.json "d['plan_verdict']=='ok'" 0
  run autorelease "";              check "auto_release observed -> unsafe_release_type, blocked, exit 2" 2 "$rc" review-plan.json "d['plan_verdict']=='blocked' and d['ios']=='unsafe_release_type' and d['observed']['auto_release'] is True" 0
  run submitted "";                check "already submitted -> plan blocked (nothing to do)" 2 "$rc" review-plan.json "d['ios']=='already_submitted'" 0
  run poison "";                   check "poisoned observe -> red exit 1, verdict words say unreadable" 1 "$rc" review-plan.json "d['plan_verdict']=='blocked' and d['ios']=='observe_unreadable' and d['n'] is None" 0
  run ok "" RCM_INPUT_MODE=submit; check "submit without typed N -> exit 2, no submit call" 2 "$rc" review.json "d['overall_status']=='failed' and d['auto_release'] is False" 0
  run ok "" RCM_INPUT_MODE=submit RCM_INPUT_CONFIRM_BUILD_NUMBER=180
                                   check "typed 180, store holds 181 -> exit 3, no submit call" 3 "$rc" review.json "d['overall_status']=='failed' and d['platforms']['ios']['reason']=='confirmation_mismatch'" 0
  run ok 175 RCM_INPUT_MODE=submit RCM_INPUT_CONFIRM_BUILD_NUMBER=181
                                   check "plan said 175, store holds 181 -> drift exit 4" 4 "$rc" review.json "d['platforms']['ios']['reason']=='store_drift'" 0
  run ok "" RCM_INPUT_MODE=submit RCM_INPUT_CONFIRM_BUILD_NUMBER=181
                                   check "submit both, Android unconfirmed -> ios submitted, android skipped, exit 6" 6 "$rc" review.json "d['overall_status']=='partial' and d['platforms']['ios']['status']=='submitted' and d['platforms']['android']['reason']=='managed_publishing_unconfirmed' and d['auto_release'] is False and d['phased_release'] is True" 1
  run ok "" RCM_INPUT_MODE=submit RCM_INPUT_CONFIRM_BUILD_NUMBER=181 RCM_INPUT_PLAY_MANAGED_PUBLISHING=confirmed-on RCM_INPUT_PHASED=0 RCM_INPUT_LISTING=full
                                   check "submit both with confirmed-on -> submitted, exit 0" 0 "$rc" review.json "d['overall_status']=='submitted' and d['phased_release'] is False" 2
  grep -q 'store_submit android 181 1.0.1 full 0' "$t/calls" || { echo "FAIL listing/phased not passed to store_submit"; fails=$((fails+1)); }
  run submitted "" RCM_INPUT_MODE=submit RCM_INPUT_CONFIRM_BUILD_NUMBER=181
                                   check "already submitted -> noop exit 5, no submit call" 5 "$rc" review.json "d['overall_status']=='noop'" 0
  run fail "" RCM_INPUT_MODE=submit RCM_INPUT_CONFIRM_BUILD_NUMBER=181 RCM_INPUT_PLATFORM=ios
                                   check "store_submit fails -> failed exit 1" 1 "$rc" review.json "d['overall_status']=='failed' and d['platforms']['ios']['status']=='failed'" 1
  run autorelease "" RCM_INPUT_MODE=submit RCM_INPUT_CONFIRM_BUILD_NUMBER=181 RCM_INPUT_PLAY_MANAGED_PUBLISHING=confirmed-on
                                   check "auto_release observed in submit -> blocked, no submit call" 2 "$rc" review.json "d['platforms']['ios']['reason']=='unsafe_release_type'" 0
  run ok "" "$SECRETS_ENV=$t/none"; check "no secrets dir -> exit 2, store untouched" 2 "$rc" review-plan.json "d['ios']=='secrets_unreadable'" 0
  [ ! -e "$t/calls" ] || { echo "FAIL store read without secrets"; fails=$((fails+1)); }
  # listing_json — the copy edited in the web UI (version page): a file for the hooks, its fields in the preview
  run ok "" RCM_INPUT_LISTING_JSON='{"ios": {"subtitle": "X", "whats_new": "a\nb"}, "android": {"title": "T", "graphics": [{"path": "g.png"}]}}'
                                   check "listing_json in plan -> listing.json written, fields echoed in preview" 0 "$rc" review-plan.json "d['listing']['preview'][:4]==['ios.subtitle: X', 'ios.whats_new: a b', 'android.title: T', 'android.graphics: 1 file(s)'] and d['listing']['diff']==['(shim) diff line']" 0
  python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert d['ios']['subtitle']=='X'" "$t/work/listing.json" || { echo "FAIL listing.json missing or wrong"; fails=$((fails+1)); }
  run ok "" RCM_INPUT_LISTING_JSON='{"ios": {"subtitle": "X"}}' RCM_INPUT_MODE=submit RCM_INPUT_CONFIRM_BUILD_NUMBER=181 RCM_INPUT_PLATFORM=ios
                                   check "listing_json in submit -> path handed to store_submit" 0 "$rc" review.json "d['overall_status']=='submitted'" 1
  grep -q "^store_submit ios 181 1.0.1 notes-only 1 $t/work/listing.json\$" "$t/calls" || { echo "FAIL listing.json path not passed to store_submit"; cat "$t/calls"; fails=$((fails+1)); }
  run ok "" RCM_INPUT_LISTING_JSON='[1, 2]'; check "listing_json not an object -> usage exit 2" 2 "$rc" review-plan.json "d['plan_verdict']=='blocked'" 0
  run ok "";                       check "no listing_json -> no listing.json, preview from the hook only" 0 "$rc" review-plan.json "d['listing']['preview']==['(shim) preview line']" 0
  [ ! -e "$t/work/listing.json" ] || { echo "FAIL listing.json written without listing_json"; fails=$((fails+1)); }
  # 두 스토어 버전 이름 — 플랫폼마다 자기 이름으로 제출한다(계약 §2 「Two store version names」)
  run ok "" RCM_INPUT_MODE=submit RCM_INPUT_CONFIRM_BUILD_NUMBER=181 RCM_INPUT_PLAY_MANAGED_PUBLISHING=confirmed-on RCM_INPUT_BUILD_NAME=1.1.1 RCM_INPUT_BUILD_NAME_ANDROID=1.0.1
                                   check "two store names -> ios 1.1.1 · android 1.0.1" 0 "$rc" review.json "d['overall_status']=='submitted'" 2
  grep -q '^store_submit ios 181 1.1.1 notes-only 1' "$t/calls" && grep -q '^store_submit android 181 1.0.1 notes-only 1' "$t/calls" \
    || { echo "FAIL per-platform build name not handed to store_submit"; cat "$t/calls"; fails=$((fails+1)); }
  run ok "" RCM_INPUT_MODE=submit RCM_INPUT_CONFIRM_BUILD_NUMBER=181 RCM_INPUT_PLAY_MANAGED_PUBLISHING=confirmed-on RCM_INPUT_BUILD_NAME=1.1.1 RCM_INPUT_BUILD_NAME_ANDROID=
                                   check "empty build_name_android -> both stores get 1.1.1" 0 "$rc" review.json "d['overall_status']=='submitted'" 2
  grep -q '^store_submit android 181 1.1.1 notes-only 1' "$t/calls" || { echo "FAIL android did not fall back to build_name"; cat "$t/calls"; fails=$((fails+1)); }
  run ok "" RCM_INPUT_BUILD_NAME_ANDROID=1.0;  check "build_name_android not X.Y.Z -> usage exit 2" 2 "$rc" review-plan.json "d['plan_verdict']=='blocked'" 0
  rm -rf "$t"
  [ "$fails" = 0 ] && { echo "[release_review] selftest PASS — plan by default, typed N enforced, Android needs the human statement, listing_json reaches the hook, each store gets its own name, poison goes red"; return 0; }
  echo "[release_review] selftest FAIL ($fails)"; return 1
}

case "${1:-}" in --selftest) WRITTEN=1; selftest;; "") main;; *) usage;; esac
