#!/usr/bin/env bash
# generated by rcm-store-connect — release_version.sh: rcm role `version`: prefill (read-only), create, delete.
#
#   Runs in the workspace rcm made from a git_ref (repository root). Inputs arrive as environment variables:
#     RCM_INPUT_MODE=prefill|create|delete   default prefill — the preset default is prefill and must stay so
#     RCM_INPUT_IOS_VERSION=X.Y.Z            create: the App Store version to create (empty = do not touch iOS)
#     RCM_INPUT_ANDROID_VERSION=X.Y.Z        create: the Android version name to draft (empty = do not touch Android)
#     RCM_INPUT_ASC_VERSION_ID=<id>          delete: the App Store Connect version id to delete
#   Secrets: the folder rcm hands over in ${{secrets_env}}. Never printed.
#
#   Writes (build/.rcm-release/, RELEASE_WORK overrides) HOWEVER THE RUN ENDS:
#     prefill.json   mode=prefill · create — the live listing copy the new version starts from
#     version.json   mode=create · delete — what was created / deleted (or error = why nothing was)
#   Exit codes (docs/release-contract.md §2):
#     0 ok · 1 failed · 2 environment / usage · 3 already exists (an editable ASC version of that name)
#     4 not deletable (the version was submitted)
#   Markers: ::rcm::steps::3 · ::rcm::step::… · ::rcm::summary::… last.
#
#   Safety built in — keep it:
#     · mode=prefill never calls store_version_create() or store_version_delete(); it only reads.
#     · create without a version name exits 2 before any store call; delete without an id exits 2.
#     · Google Play has no version object: the Android draft lives in rcm and reaches the store at upload /
#       submit. store_version_create() only records the name for Android.
#     · There is no release / submit / rollout call in this file, and none may be added for rcm.
#
#   --selftest   shims replace the store; proves: prefill falls back to store/ files, create calls the hook
#                and writes version.json, an existing version -> 3, a submitted version -> 4, a bad name -> 2.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; SELF="$HERE/$(basename "${BASH_SOURCE[0]}")"; ROOT="$(cd "$HERE/../.." && pwd)"; cd "$ROOT"

CONTRACT="${RCM_CONTRACT_PY:-$HERE/rcm_contract.py}"
WORK="${RELEASE_WORK:-$ROOT/build/.rcm-release}"
STORE_DIR="${RELEASE_STORE_DIR:-$ROOT/store}"           # listing copy in the repository — the prefill fallback
LOCALE="${RELEASE_LOCALE:-ko}"                            # one locale (the page keys fields without a language)
SECRETS_ENV="{{secrets_env}}"
# 안 채워진 템플릿(`{{secrets_env}}` 그대로)도 셀프테스트로 돌아야 한다 — bash 5 는 이름이
# 아닌 것의 간접 확장을 거부한다. 이름이 아니면 셀프테스트용 이름을 쓴다(채운 사본은 그대로).
case "$SECRETS_ENV" in ""|[0-9]*|*[!A-Za-z0-9_]*) SECRETS_ENV=RCM_TEMPLATE_SECRETS_DIR;; esac
SECRETS_DIR="${!SECRETS_ENV:-}"
SHIM="${RELEASE_SHIM:-}"                                 # selftest only: ok | files | exists | submitted | fail
SHIM_CALLS="${RELEASE_SHIM_CALLS:-/dev/null}"
WRITTEN=0
MODE="${RCM_INPUT_MODE:-prefill}"

usage() {
  echo "usage: [RCM_INPUT_MODE=prefill|create|delete] [RCM_INPUT_IOS_VERSION=X.Y.Z] [RCM_INPUT_ANDROID_VERSION=X.Y.Z]" >&2
  echo "       [RCM_INPUT_ASC_VERSION_ID=<id>] release_version.sh | release_version.sh --selftest" >&2
  exit 2
}

# ── project hooks — the only places that talk to a store ─────────────────────────────────────────────
# store_prefill: print ONE JSON object with the LIVE listing copy, read-only:
#   { "source": "asc_live:1.1.0 · play_listing", "locale": "ko",
#     "ios": { "subtitle", "promotional_text", "description", "keywords", "support_url", "marketing_url",
#              "whats_new", "screenshots": [ {"path": "…"} ] } | null,
#     "android": { "title", "short_description", "full_description", "whats_new", "graphics": [] } | null }
#   Exit non-zero when the stores cannot be read — the script then falls back to the files under store/.
store_prefill() {
  if [ -n "$SHIM" ]; then shim_store_prefill; return $?; fi
  # TODO(project): read the live App Store version's localizations ($LOCALE) and the Play listing with the
  #   credentials in "$SECRETS_DIR" and print the object above. Read-only. Until then the fallback below reads
  #   the repository's store/ files, so delete the `return 1` when done.
  return 1
}
# store_version_create IOS_VERSION ANDROID_VERSION: create the editable App Store version (when IOS_VERSION is
#   not empty) and record the Android name. Print ONE JSON object:
#   { "ios": {"version": "1.1.1", "asc_version_id": "<id>", "state": "PREPARE_FOR_SUBMISSION"} | null,
#     "android": {"version": "1.0.1"} | null }
#   Exit 0 created · 3 an editable version of that name already exists (print its id in "ios" if you can) ·
#   anything else = failed. Must NOT submit, release or upload.
store_version_create() {
  if [ -n "$SHIM" ]; then shim_store_version_create "$@"; return $?; fi
  # TODO(project): e.g. POST /v1/appStoreVersions (platform IOS, versionString=$1) with the ASC key from
  #   "$SECRETS_DIR"; on 409 / an existing PREPARE_FOR_SUBMISSION version of the same name exit 3.
  #   Android ($2) has no store object: just echo it back. Delete the two lines below when done.
  echo "store_version_create() is not implemented — fill the TODO(project) block in scripts/release/release_version.sh" >&2
  return 1
}
# store_version_delete ASC_VERSION_ID: delete ONE editable App Store version. Exit 0 deleted · 4 not deletable
#   (already submitted / in review / live) · anything else = failed. Never deletes a submitted version.
store_version_delete() {
  if [ -n "$SHIM" ]; then shim_store_version_delete "$@"; return $?; fi
  # TODO(project): read the version state first; DELETE /v1/appStoreVersions/$1 only when it is
  #   PREPARE_FOR_SUBMISSION (or another editable state), otherwise exit 4. Delete the two lines below when done.
  echo "store_version_delete() is not implemented — fill the TODO(project) block in scripts/release/release_version.sh" >&2
  return 1
}

# ── selftest shims ───────────────────────────────────────────────────────────────────────────────────
shim_store_prefill() {
  echo "store_prefill" >>"$SHIM_CALLS"
  case "$SHIM" in
    ok|exists|submitted) echo '{"source": "asc_live:1.1.0 · play_listing", "locale": "ko", "ios": {"subtitle": "Live subtitle", "whats_new": "Fixes", "screenshots": [{"path": "store/screenshots/ios/ko/0.png"}]}, "android": {"title": "App", "short_description": "Short", "graphics": []}}';;
    files|fail) return 7;;      # unreadable -> the script falls back to store/ files
    *) echo "unknown RELEASE_SHIM=$SHIM" >&2; return 9;;
  esac
}
shim_store_version_create() {
  echo "store_version_create '$1' '$2'" >>"$SHIM_CALLS"
  case "$SHIM" in
    exists) echo '{"ios": {"version": "'"$1"'", "asc_version_id": "old777", "state": "PREPARE_FOR_SUBMISSION"}, "android": null}'; return 3;;
    fail)   return 1;;
    *)      echo '{"ios": '"$([ -n "$1" ] && echo '{"version": "'"$1"'", "asc_version_id": "abc123", "state": "PREPARE_FOR_SUBMISSION"}' || echo null)"', "android": '"$([ -n "$2" ] && echo '{"version": "'"$2"'"}' || echo null)"'}';;
  esac
}
shim_store_version_delete() {
  echo "store_version_delete '$1'" >>"$SHIM_CALLS"
  case "$SHIM" in submitted) return 4;; fail) return 1;; *) return 0;; esac
}

# ── contract plumbing ────────────────────────────────────────────────────────────────────────────────
step()     { echo "::rcm::step::$1"; }
step_end() { echo "::rcm::step-end::$1"; }
finish()   { echo "::rcm::summary::$1"; exit "$2"; }
write_version() {  # $1 mode · $2 ios json|'' · $3 android json|'' · $4 error|''
  local args=(write version --out "$WORK/version.json" --mode "$1" --extra-json "{\"exit_code\": ${EXIT_CODE:-null}}")
  [ -n "$2" ] && args+=(--ios-json "$2")
  [ -n "$3" ] && args+=(--android-json "$3")
  [ -n "${4:-}" ] && args+=(--error "$4")
  python3 "$CONTRACT" "${args[@]}" && WRITTEN=1
}
write_prefill() {  # $1 source · $2 ios json|'' · $3 android json|''
  local args=(write prefill --out "$WORK/prefill.json" --source "$1" --locale "$LOCALE")
  [ -n "$2" ] && args+=(--ios-json "$2")
  [ -n "$3" ] && args+=(--android-json "$3")
  python3 "$CONTRACT" "${args[@]}"
}
on_exit() {  # 마지막 안전망 — create · delete 는 어떤 경로로 끝나든 version.json 이 남는다
  local rc=$?
  [ "$WRITTEN" = 1 ] && return 0
  case "$MODE" in create|delete) ;; *) return 0;; esac
  EXIT_CODE=$rc write_version "$MODE" "" "" "aborted_exit_$rc" >/dev/null 2>&1 || true
}
trap on_exit EXIT

# store/ 파일에서 문안을 읽는 폴백 — store_prefill() 이 없거나 실패했을 때. 파일 배치는 프로젝트마다 다르니
# 여기(또는 store_prefill 의 TODO) 를 고친다: 기본은 store/<platform>/<locale>/<key>.txt 와 screenshots/.
prefill_from_files() {  # prints {"ios": …|null, "android": …|null}
  python3 - "$STORE_DIR" "$LOCALE" <<'PY'
import glob, json, os, sys
root, locale = sys.argv[1:3]
keys = {"ios": ["subtitle", "promotional_text", "description", "keywords", "support_url", "marketing_url", "whats_new"],
        "android": ["title", "short_description", "full_description", "whats_new"]}
images = {"ios": "screenshots", "android": "graphics"}
out = {}
for plat, names in keys.items():
    folder = os.path.join(root, plat, locale)
    doc = {}
    for k in names:
        path = os.path.join(folder, k + ".txt")
        if os.path.isfile(path):
            doc[k] = open(path, encoding="utf-8").read().rstrip("\n")
    shots = sorted(glob.glob(os.path.join(root, "screenshots", plat, locale, "*.png")))
    if shots:
        doc[images[plat]] = [{"path": os.path.relpath(p, os.getcwd())} for p in shots]
    out[plat] = doc or None
print(json.dumps(out, ensure_ascii=False))
PY
}
json_field() { python3 -c 'import json,sys; v=json.load(open(sys.argv[1])).get(sys.argv[2]); print("" if v is None else json.dumps(v, ensure_ascii=False))' "$1" "$2"; }

do_prefill() {  # writes prefill.json; returns 0 when written (live or files)
  local raw="$WORK/prefill-raw.json" source ios android
  if [ -n "$SECRETS_DIR" ] && [ -d "$SECRETS_DIR" ] && store_prefill >"$raw" 2>/dev/null \
     && python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); assert isinstance(d, dict) and isinstance(d.get("source"), str)' "$raw" 2>/dev/null; then
    source="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["source"])' "$raw")"
  else
    echo "  store_prefill() unavailable — reading the listing copy from ${STORE_DIR#"$ROOT"/}/"
    prefill_from_files >"$raw"
    source="file:${STORE_DIR#"$ROOT"/}"
  fi
  ios="$(json_field "$raw" ios)"; android="$(json_field "$raw" android)"
  write_prefill "$source" "$ios" "$android"
}

main() {
  local ios_v="${RCM_INPUT_IOS_VERSION:-}" android_v="${RCM_INPUT_ANDROID_VERSION:-}" asc_id="${RCM_INPUT_ASC_VERSION_ID:-}"
  local res rc ios android
  case "$MODE" in prefill|create|delete) ;; *) echo "RCM_INPUT_MODE must be prefill|create|delete, got '$MODE'" >&2; usage;; esac
  [ -z "$ios_v" ] || [[ "$ios_v" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "RCM_INPUT_IOS_VERSION must be X.Y.Z, got '$ios_v'" >&2; usage; }
  [ -z "$android_v" ] || [[ "$android_v" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "RCM_INPUT_ANDROID_VERSION must be X.Y.Z, got '$android_v'" >&2; usage; }
  if [ "$MODE" = create ] && [ -z "$ios_v" ] && [ -z "$android_v" ]; then echo "mode=create needs RCM_INPUT_IOS_VERSION and/or RCM_INPUT_ANDROID_VERSION" >&2; usage; fi
  if [ "$MODE" = delete ] && [ -z "$asc_id" ]; then echo "mode=delete needs RCM_INPUT_ASC_VERSION_ID" >&2; usage; fi
  [ -f "$CONTRACT" ] || { echo "missing $CONTRACT — reinstall with /rcm-store-connect" >&2; exit 2; }
  mkdir -p "$WORK"
  echo "::rcm::steps::3"

  step "preflight"
  if [ "$MODE" != prefill ] && { [ -z "$SECRETS_DIR" ] || [ ! -d "$SECRETS_DIR" ]; }; then
    step_end fail
    EXIT_CODE=2 write_version "$MODE" "" "" "secrets folder missing (\$$SECRETS_ENV)"
    finish "BLOCKED(env) — secrets folder missing (\$$SECRETS_ENV)" 2
  fi
  step_end ok

  if [ "$MODE" = prefill ]; then
    step "prefill"
    do_prefill || { step_end fail; finish "failed — could not write prefill.json (see log)" 1; }
    step_end ok
    step "done"; step_end ok
    finish "prefill ok — $(json_field "$WORK/prefill.json" source) (read-only; nothing created)" 0
  fi

  if [ "$MODE" = delete ]; then
    step "delete"
    rc=0; store_version_delete "$asc_id" || rc=$?
    case "$rc" in
      0) step_end ok
         step "version.json"
         EXIT_CODE=0 write_version delete "{\"version\": \"${ios_v:-?}\", \"asc_version_id\": \"$asc_id\", \"state\": \"deleted\"}" ""
         step_end ok
         finish "deleted — App Store version $asc_id (${ios_v:-name unknown})" 0;;
      4) step_end fail
         EXIT_CODE=4 write_version delete "" "" "not deletable: App Store version $asc_id was submitted (exit 4)"
         finish "not deletable — version $asc_id was submitted; nothing changed (exit 4)" 4;;
      *) step_end fail
         EXIT_CODE=1 write_version delete "" "" "store_version_delete() failed (exit $rc)"
         finish "failed — store_version_delete() exit $rc" 1;;
    esac
  fi

  # ── create ──
  step "create"
  res="$WORK/version-create.json"
  rc=0; store_version_create "$ios_v" "$android_v" >"$res" || rc=$?
  ios=""; android=""
  if [ "$rc" = 0 ] || [ "$rc" = 3 ]; then
    ios="$(json_field "$res" ios 2>/dev/null || true)"; android="$(json_field "$res" android 2>/dev/null || true)"
  fi
  case "$rc" in
    0) step_end ok;;
    3) step_end fail
       EXIT_CODE=3 write_version create "$ios" "" "already exists: an editable App Store version named $ios_v (exit 3)"
       finish "already exists — an editable App Store version named $ios_v is there; open it or delete it first (exit 3)" 3;;
    *) step_end fail
       EXIT_CODE=1 write_version create "" "" "store_version_create() failed (exit $rc)"
       finish "failed — store_version_create() exit $rc; nothing recorded" 1;;
  esac
  step "prefill + version.json"
  if ! EXIT_CODE=0 write_version create "$ios" "$android"; then
    step_end fail
    EXIT_CODE=1 write_version create "" "" "store_version_create() output violates its contract (see log)"
    finish "failed — store_version_create() output violates its contract; check the store by hand" 1
  fi
  do_prefill || echo "  prefill.json not written — the page falls back to the listing preview" >&2
  step_end ok
  finish "created — ios=${ios_v:--} android=${android_v:--} (nothing submitted)" 0
}

# ── selftest ─────────────────────────────────────────────────────────────────────────────────────────
selftest() {
  local t rc fails=0
  t="$(mktemp -d)"; mkdir -p "$t/secrets" "$t/store/ios/ko" "$t/store/android/ko" "$t/store/screenshots/ios/ko"
  printf 'From file\n' >"$t/store/ios/ko/subtitle.txt"; printf 'File title\n' >"$t/store/android/ko/title.txt"; : >"$t/store/screenshots/ios/ko/0.png"
  check() {  # $1 label · $2 expected rc · $3 actual · $4 file · $5 assertion ('' = skip) · $6 expected store-call count (create+delete)
    if [ "$2" != "$3" ]; then echo "FAIL $1: exit $3, expected $2"; cat "$t/out"; fails=$((fails+1)); return; fi
    if [ -n "$5" ] && ! python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert $5, d" "$t/work/$4"; then
      echo "FAIL $1: $4 assertion failed: $5"; fails=$((fails+1)); return
    fi
    local calls; calls="$(grep -c '^store_version_' "$t/calls" 2>/dev/null || true)"; calls="${calls:-0}"
    if [ "$6" != "$calls" ]; then echo "FAIL $1: store_version_* called $calls times, expected $6"; fails=$((fails+1)); return; fi
    echo "  ok  $1"
  }
  run() {  # $1 shim · rest env
    local shim="$1"; shift
    rm -rf "$t/work" "$t/calls"; mkdir -p "$t/work"; rc=0
    env RELEASE_SHIM="$shim" RELEASE_SHIM_CALLS="$t/calls" RELEASE_WORK="$t/work" RELEASE_STORE_DIR="$t/store" \
        "$SECRETS_ENV=$t/secrets" "$@" bash "$SELF" >"$t/out" 2>&1 || rc=$?
  }
  echo "[release_version] selftest ($SECRETS_ENV)"
  run files;                       check "no mode -> prefill from store/ files, no store call" 0 "$rc" prefill.json "d['source'].startswith('file:') and d['locale']=='ko' and d['ios']['subtitle']=='From file' and d['ios']['screenshots'][0]['path'].endswith('0.png') and d['android']['title'].endswith('title')" 0
  [ ! -e "$t/work/version.json" ] || { echo "FAIL prefill wrote version.json"; fails=$((fails+1)); }
  run ok;                          check "prefill from the live store" 0 "$rc" prefill.json "d['source']=='asc_live:1.1.0 · play_listing' and d['ios']['subtitle']=='Live subtitle' and d['android']['title']=='App'" 0
  run files "$SECRETS_ENV=$t/none"; check "prefill without secrets -> files, still exit 0" 0 "$rc" prefill.json "d['source'].startswith('file:')" 0
  run ok RCM_INPUT_MODE=create RCM_INPUT_IOS_VERSION=1.1.1 RCM_INPUT_ANDROID_VERSION=1.0.1
                                   check "create both -> version.json + prefill.json, exit 0" 0 "$rc" version.json "d['mode']=='create' and d['ios']['version']=='1.1.1' and d['ios']['asc_version_id']=='abc123' and d['android']['version']=='1.0.1' and d['error'] is None" 1
  grep -q "^store_version_create '1.1.1' '1.0.1'" "$t/calls" || { echo "FAIL create hook got the wrong names"; fails=$((fails+1)); }
  python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert d['ios']['subtitle']=='Live subtitle'" "$t/work/prefill.json" || { echo "FAIL create did not write prefill.json"; fails=$((fails+1)); }
  run ok RCM_INPUT_MODE=create RCM_INPUT_ANDROID_VERSION=1.0.1
                                   check "create Android only -> ios null" 0 "$rc" version.json "d['ios'] is None and d['android']['version']=='1.0.1'" 1
  run exists RCM_INPUT_MODE=create RCM_INPUT_IOS_VERSION=1.1.1
                                   check "editable version already exists -> exit 3, its id recorded" 3 "$rc" version.json "d['mode']=='create' and 'already exists' in d['error'] and d['ios']['asc_version_id']=='old777' and d['android'] is None" 1
  run fail RCM_INPUT_MODE=create RCM_INPUT_IOS_VERSION=1.1.1
                                   check "create hook fails -> exit 1, both null + error" 1 "$rc" version.json "d['ios'] is None and d['android'] is None and 'failed' in d['error']" 1
  run ok RCM_INPUT_MODE=create;    check "create without any name -> usage exit 2, no store call" 2 "$rc" "" "" 0
  run ok RCM_INPUT_MODE=create RCM_INPUT_IOS_VERSION=1.1
                                   check "bad name -> usage exit 2, no store call" 2 "$rc" "" "" 0
  run ok RCM_INPUT_MODE=create RCM_INPUT_IOS_VERSION=1.1.1 "$SECRETS_ENV=$t/none"
                                   check "create without secrets -> exit 2, store untouched" 2 "$rc" version.json "d['ios'] is None and 'secrets' in d['error']" 0
  run ok RCM_INPUT_MODE=delete RCM_INPUT_ASC_VERSION_ID=abc123 RCM_INPUT_IOS_VERSION=1.1.1
                                   check "delete editable -> exit 0" 0 "$rc" version.json "d['mode']=='delete' and d['ios']['asc_version_id']=='abc123' and d['ios']['state']=='deleted' and d['android'] is None" 1
  grep -q "^store_version_delete 'abc123'" "$t/calls" || { echo "FAIL delete hook got the wrong id"; fails=$((fails+1)); }
  run submitted RCM_INPUT_MODE=delete RCM_INPUT_ASC_VERSION_ID=abc123
                                   check "delete a submitted version -> exit 4, nothing changed" 4 "$rc" version.json "d['mode']=='delete' and d['ios'] is None and 'not deletable' in d['error']" 1
  run ok RCM_INPUT_MODE=delete;    check "delete without id -> usage exit 2, no store call" 2 "$rc" "" "" 0
  run ok RCM_INPUT_MODE=publish;   check "unknown mode -> usage exit 2" 2 "$rc" "" "" 0
  rm -rf "$t"
  [ "$fails" = 0 ] && { echo "[release_version] selftest PASS — prefill by default, create/delete only by name or id, submitted versions stay"; return 0; }
  echo "[release_version] selftest FAIL ($fails)"; return 1
}

case "${1:-}" in --selftest) WRITTEN=1; selftest;; "") main;; *) usage;; esac
