#!/usr/bin/env bash
# generated by rcm-store-connect — release_plan.sh: rcm role `plan`: read-only store snapshot -> plan.json.
#
#   Runs in the workspace rcm made from a git_ref (repository root). Inputs arrive as environment variables:
#     RCM_INPUT_BUILD_NAME=X.Y.Z   bash scripts/release/release_plan.sh
#   Secrets: the folder rcm hands over in ${{secrets_env}} (files, one per secret). Never printed.
#
#   Writes  build/.rcm-release/plan.json  (RELEASE_WORK overrides the folder) HOWEVER THE RUN ENDS:
#     n == null always comes with a non-empty blockers[]; a run that dies early still leaves a plan.json.
#   Exit codes (docs/release-contract.md §2): 0 ok · 1 blocked (plan.json written, n = null) · 2 environment.
#   Markers: ::rcm::steps::3 · ::rcm::step::<name> · ::rcm::step-end::ok|fail · ::rcm::summary::… last.
#
#   Read-only by construction: this script has no upload, tag, commit or push path. It computes N as
#   (highest build number the store knows) + 1 — YOUR store_snapshot() below supplies that number.
#
#   --selftest   proves the contract without a store: shims replace store_snapshot(); a poisoned snapshot
#                must end red (exit 1, plan.json n = null, blocker B-CONTRACT) and never a fake number.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; SELF="$HERE/$(basename "${BASH_SOURCE[0]}")"; ROOT="$(cd "$HERE/../.." && pwd)"; cd "$ROOT"

CONTRACT="${RCM_CONTRACT_PY:-$HERE/rcm_contract.py}"      # stdlib helper installed next to this script
WORK="${RELEASE_WORK:-$ROOT/build/.rcm-release}"
OUT="$WORK/plan.json"
SECRETS_ENV="{{secrets_env}}"                            # name of the env var rcm sets (profile.secrets_dir_env)
# 안 채워진 템플릿(`{{secrets_env}}` 그대로)도 셀프테스트로 돌아야 한다 — bash 5 는 이름이
# 아닌 것의 간접 확장을 거부한다. 이름이 아니면 셀프테스트용 이름을 쓴다(채운 사본은 그대로).
case "$SECRETS_ENV" in ""|[0-9]*|*[!A-Za-z0-9_]*) SECRETS_ENV=RCM_TEMPLATE_SECRETS_DIR;; esac
SECRETS_DIR="${!SECRETS_ENV:-}"
SHIM="${RELEASE_SHIM:-}"                                 # selftest only: ok | blocked | poison | unreadable
SHIM_CALLS="${RELEASE_SHIM_CALLS:-/dev/null}"
WRITTEN=0

usage() { echo "usage: RCM_INPUT_BUILD_NAME=X.Y.Z release_plan.sh | release_plan.sh --selftest" >&2; exit 2; }

# ── project hooks — the only place that talks to a store ──────────────────────────────────────────────
# Contract for store_snapshot(): print ONE JSON object on stdout and exit 0 when the store was read:
#   { "max_build": <int|null>,   highest build number on any track / any version, both stores together
#     "first_release": <bool>,   true when nothing is live yet
#     "store": <object|null>,    shown raw by the page (asc_live, asc_editing, play tracks, …)
#     "blockers": [ {"code": "B-…", "text": "…"} ],   reasons the release must not proceed (empty = none)
#     "warnings": [ {"code": "W-…", "text": "…"} ] }
# Exit non-zero when the store cannot be read (the script turns that into blocker B-STORE, exit 1).
store_snapshot() {
  if [ -n "$SHIM" ]; then shim_store_snapshot; return $?; fi
  # TODO(project): read App Store Connect / Google Play with the credentials in "$SECRETS_DIR" and print the
  #   JSON object described above. Typical sources: an existing fastlane lane that lists builds, a store CLI,
  #   or a python script the project already has. Read-only calls only. Delete the echo below when done.
  echo '{"max_build": null, "first_release": false, "store": null,'
  echo ' "blockers": [{"code": "B-TODO", "text": "store_snapshot() is not implemented — fill the TODO(project) block in scripts/release/release_plan.sh"}],'
  echo ' "warnings": []}'
}

# ── selftest shims (untouched in production; RELEASE_SHIM is never set by rcm) ───────────────────────
shim_store_snapshot() {
  echo "store_snapshot" >>"$SHIM_CALLS"
  case "$SHIM" in
    ok)         echo '{"max_build": 180, "first_release": false, "store": {"asc_live": "1.0.0"}, "blockers": [], "warnings": []}';;
    blocked)    echo '{"max_build": 180, "first_release": false, "store": {}, "blockers": [{"code": "B-PLAYBUSY", "text": "a release is in progress"}], "warnings": []}';;
    poison)     echo '{"max_build": "18l", "first_release": "no", "store": {}, "blockers": [], "warnings": []}';;
    unreadable) return 7;;
    *) echo "unknown RELEASE_SHIM=$SHIM" >&2; return 9;;
  esac
}

# ── contract plumbing ────────────────────────────────────────────────────────────────────────────────
step()     { echo "::rcm::step::$1"; }
step_end() { echo "::rcm::step-end::$1"; }
finish()   { echo "::rcm::summary::$1"; exit "$2"; }

# 마지막 안전망: 어떤 경로로 끝나든 plan.json 이 남는다(n=null + 이유). 정상 경로는 WRITTEN=1 로 여기를 건너뛴다.
on_exit() {
  local rc=$?
  [ "$WRITTEN" = 1 ] && return 0
  [ -n "${RCM_INPUT_BUILD_NAME:-}" ] || return 0     # usage error before any input: nothing to describe
  python3 "$CONTRACT" write plan --out "$OUT" --build-name "${RCM_INPUT_BUILD_NAME}" --n null \
    --blocker "B-ABORT=release_plan.sh ended before plan.json was written (exit $rc)" >/dev/null 2>&1 || true
}
trap on_exit EXIT

main() {
  local bn="${RCM_INPUT_BUILD_NAME:-}" snap n first_release blocked
  [[ "$bn" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "RCM_INPUT_BUILD_NAME must be X.Y.Z, got '$bn'" >&2; usage; }
  [ -f "$CONTRACT" ] || { echo "missing $CONTRACT — reinstall with /rcm-store-connect" >&2; exit 2; }
  mkdir -p "$WORK"
  echo "::rcm::steps::3"

  step "preflight"
  if [ -z "$SECRETS_DIR" ] || [ ! -d "$SECRETS_DIR" ]; then
    step_end fail
    python3 "$CONTRACT" write plan --out "$OUT" --build-name "$bn" --n null \
      --blocker "B-ENV=\$$SECRETS_ENV is not a directory — add the secrets in the Store tab Settings first" && WRITTEN=1
    finish "BLOCKED(env) — secrets folder missing (\$$SECRETS_ENV)" 2
  fi
  # TODO(project): add read-only tool checks here (e.g. a store CLI on PATH). Missing tool -> same shape as above, exit 2.
  step_end ok

  step "store snapshot"
  snap="$WORK/snapshot.json"
  if ! store_snapshot >"$snap"; then
    step_end fail
    python3 "$CONTRACT" write plan --out "$OUT" --build-name "$bn" --n null \
      --blocker "B-STORE=store_snapshot() failed — the store could not be read (see log)" && WRITTEN=1
    finish "blocked — store unreadable (plan.json n=null)" 1
  fi
  step_end ok

  step "plan.json"
  # 스냅샷 → N. max_build 가 정수가 아니면 n 은 "null" 이 아니라 그 값 그대로 넘어가 계약 검증에서 걸린다 — 가짜 숫자를 쓰지 않는다.
  n="$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); m=d.get("max_build"); print("null" if m is None else (m+1 if isinstance(m,int) and not isinstance(m,bool) else m))' "$snap" 2>/dev/null || echo "unparsable")"
  first_release="$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(d.get("first_release"))' "$snap" 2>/dev/null || echo "unparsable")"
  case "$first_release" in True) first_release=1;; False) first_release=0;; esac
  blocked="$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(len(d.get("blockers") or []))' "$snap" 2>/dev/null || echo 1)"
  [ "$blocked" != 0 ] && n=null                      # 막힌 판정에는 숫자를 남기지 않는다 — 페이지가 그 N 으로 확인을 물을 수 있다
  if python3 - "$CONTRACT" "$OUT" "$bn" "$n" "$first_release" "$snap" <<'PY'
import json, subprocess, sys
contract, out, bn, n, first_release, snap = sys.argv[1:7]
d = json.load(open(snap, encoding="utf-8"))
argv = [sys.executable, contract, "write", "plan", "--out", out, "--build-name", bn, "--n", str(n),
        "--first-release", str(first_release), "--store-json", json.dumps(d.get("store"))]
for b in d.get("blockers") or []:
    argv += ["--blocker", f"{b.get('code')}={b.get('text')}"]
for w in d.get("warnings") or []:
    argv += ["--warning", f"{w.get('code')}={w.get('text')}"]
if n == "null" and not d.get("blockers"):
    argv += ["--blocker", "B-STORE=store_snapshot() returned no max_build and no blocker — nothing to plan from"]
sys.exit(subprocess.call(argv))
PY
  then
    WRITTEN=1; step_end ok
  else
    step_end fail
    # 오염된 스냅샷: 규약이 거부했다. 빨간 결과를 남기되 숫자는 절대 남기지 않는다.
    python3 "$CONTRACT" write plan --out "$OUT" --build-name "$bn" --n null \
      --blocker "B-CONTRACT=store_snapshot() output violates the plan.json contract (see log above)" && WRITTEN=1
    finish "blocked — contract violation in store_snapshot() output (plan.json n=null)" 1
  fi
  if [ "$n" = null ]; then
    finish "blocked — no build number (plan.json blockers[] says why)" 1
  fi
  finish "plan ok — $bn N=$n (read-only; nothing uploaded)" 0
}

# ── selftest ─────────────────────────────────────────────────────────────────────────────────────────
selftest() {
  local t rc fails=0
  t="$(mktemp -d)"; mkdir -p "$t/secrets" "$t/nosecrets_parent"
  check() {  # $1 label · $2 expected rc · $3 actual rc · $4 python assertion on plan.json ('' = skip)
    if [ "$2" != "$3" ]; then echo "FAIL $1: exit $3, expected $2"; cat "$t/out"; fails=$((fails+1)); return; fi
    if [ -n "$4" ] && ! python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert $4, d" "$t/work/plan.json"; then
      echo "FAIL $1: plan.json assertion failed: $4"; fails=$((fails+1)); return
    fi
    echo "  ok  $1"
  }
  run() {  # RELEASE_SHIM value, then extra env; runs this script with a throwaway work dir
    local shim="$1"; shift
    rm -rf "$t/work" "$t/calls"; rc=0
    env RELEASE_SHIM="$shim" RELEASE_SHIM_CALLS="$t/calls" RELEASE_WORK="$t/work" \
        "$SECRETS_ENV=$t/secrets" RCM_INPUT_BUILD_NAME=1.0.1 "$@" bash "$SELF" >"$t/out" 2>&1 || rc=$?
  }
  echo "[release_plan] selftest ($SECRETS_ENV)"
  run ok;         check "store max 180 -> n 181, exit 0" 0 "$rc" "d['n']==181 and d['first_release'] is False and d['schema']==1"
  grep -q '::rcm::summary::plan ok' "$t/out" || { echo "FAIL summary marker missing"; fails=$((fails+1)); }
  run blocked;    check "store blocker -> n null, exit 1" 1 "$rc" "d['n'] is None and d['blockers'][0]['code']=='B-PLAYBUSY'"
  run poison;     check "poisoned snapshot -> red, n null, B-CONTRACT" 1 "$rc" "d['n'] is None and any(b['code']=='B-CONTRACT' for b in d['blockers'])"
  run unreadable; check "store unreadable -> n null, B-STORE" 1 "$rc" "d['n'] is None and d['blockers'][0]['code']=='B-STORE'"
  run ok "$SECRETS_ENV=$t/nosecrets_parent/missing"
                  check "no secrets dir -> exit 2, store never called" 2 "$rc" "d['n'] is None and d['blockers'][0]['code']=='B-ENV'"
  [ ! -e "$t/calls" ] || { echo "FAIL store_snapshot was called without secrets"; fails=$((fails+1)); }
  run ok RCM_INPUT_BUILD_NAME=1.0; check "bad build_name -> usage exit 2" 2 "$rc" ""
  rm -rf "$t"
  [ "$fails" = 0 ] && { echo "[release_plan] selftest PASS — poisoned output goes red, n is never invented"; return 0; }
  echo "[release_plan] selftest FAIL ($fails)"; return 1
}

case "${1:-}" in --selftest) WRITTEN=1; selftest;; "") main;; *) usage;; esac
