#!/usr/bin/env bash
# generated by rcm-store-connect — release_upload.sh: rcm role `upload`: store upload -> upload.json.
#
#   Runs in the workspace rcm made from a git_ref (repository root). Inputs arrive as environment variables:
#     RCM_INPUT_BUILD_NAME=X.Y.Z            version name (required) — the representative name of the round
#     RCM_INPUT_BUILD_NAME_ANDROID=X.Y.Z    default "" — the Android version name when the two stores ship
#                                           DIFFERENT names (App Store 1.1.1 · Play 1.0.1). Empty: both stores
#                                           get RCM_INPUT_BUILD_NAME. platform_build_name() picks per platform
#     RCM_INPUT_CONFIRM_BUILD_NUMBER=N      the number a HUMAN typed in this submission (required for mode=upload)
#     RCM_INPUT_MODE=rehearsal|upload       default rehearsal — the preset default is rehearsal and must stay so
#     RCM_INPUT_PLATFORM=both|ios|android   default both
#     RCM_INPUT_ANDROID_TRACK=production|internal   default production
#     RCM_INPUT_LISTING_JSON='{"ios":{…},"android":{…}}'  default "" — the copy edited in the web UI (version page).
#                                           Not empty: written to build/.rcm-release/listing.json and handed to
#                                           store_upload() as LISTING_FILE; it wins over the store/ files
#   Secrets: the folder rcm hands over in ${{secrets_env}}. Never printed.
#
#   Writes  build/.rcm-release/upload.json  (RELEASE_WORK overrides) HOWEVER THE RUN ENDS.
#   Exit codes (docs/release-contract.md §2):
#     0 uploaded (or rehearsal complete) · 1 failed/partial · 2 environment/usage
#     3 confirmation mismatch (typed N != store max + 1) · 4 store drift (store max + 1 != plan.json n)
#   Markers: ::rcm::steps::N (known once platform is parsed) · ::rcm::step::… · ::rcm::summary::… last.
#
#   Safety built in — keep it:
#     · rehearsal mode never calls store_upload(); upload.json then says status = "rehearsal".
#     · mode=upload without a typed confirmation exits 2 before any store call.
#     · the confirmation is compared against the store as it is NOW, not against a remembered value.
#     · there is no rollout / release / promote call anywhere in this file, and none may be added for rcm.
#
#   --selftest   shims replace the store; proves: default is rehearsal (no upload call), upload needs the typed N,
#                mismatch -> 3, drift -> 4, partial -> 1, poisoned store answer -> red (never a fake success),
#                and each store gets its own version name when the two differ.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; SELF="$HERE/$(basename "${BASH_SOURCE[0]}")"; ROOT="$(cd "$HERE/../.." && pwd)"; cd "$ROOT"

CONTRACT="${RCM_CONTRACT_PY:-$HERE/rcm_contract.py}"
WORK="${RELEASE_WORK:-$ROOT/build/.rcm-release}"
OUT="$WORK/upload.json"
SECRETS_ENV="{{secrets_env}}"
SECRETS_DIR="${!SECRETS_ENV:-}"
SHIM="${RELEASE_SHIM:-}"                                 # selftest only: ok | partial | poison | fail
SHIM_CALLS="${RELEASE_SHIM_CALLS:-/dev/null}"
SHIM_MAX="${RELEASE_SHIM_MAX:-180}"
WRITTEN=0
LISTING_FILE=""                                          # $WORK/listing.json when RCM_INPUT_LISTING_JSON is not empty

usage() {
  echo "usage: RCM_INPUT_BUILD_NAME=X.Y.Z [RCM_INPUT_BUILD_NAME_ANDROID=X.Y.Z] [RCM_INPUT_MODE=rehearsal|upload]" >&2
  echo "       [RCM_INPUT_CONFIRM_BUILD_NUMBER=N] [RCM_INPUT_PLATFORM=both|ios|android]" >&2
  echo "       [RCM_INPUT_ANDROID_TRACK=production|internal] [RCM_INPUT_LISTING_JSON='{…}']" >&2
  echo "       release_upload.sh | release_upload.sh --selftest" >&2
  exit 2
}
# platform_build_name PLATFORM: the version name THAT store gets. One round may ship different names
#   to the two stores (docs/release-contract.md §2 «Two store version names»): android takes
#   RCM_INPUT_BUILD_NAME_ANDROID when it is not empty, anything else takes RCM_INPUT_BUILD_NAME.
platform_build_name() {
  if [ "$1" = android ] && [ -n "${RCM_INPUT_BUILD_NAME_ANDROID:-}" ]; then
    printf '%s\n' "$RCM_INPUT_BUILD_NAME_ANDROID"
  else
    printf '%s\n' "${RCM_INPUT_BUILD_NAME:-}"
  fi
}

# ── project hooks — the only places that talk to a store ─────────────────────────────────────────────
# store_max_build(): print ONE integer — the highest build number the stores know right now (both stores,
#   any track). Exit non-zero when unreadable. Read-only.
store_max_build() {
  if [ -n "$SHIM" ]; then shim_store_max_build; return $?; fi
  # TODO(project): same read as release_plan.sh store_snapshot() but only the number, e.g. reuse the lane /
  #   script that lists builds and print max(asc, play). Delete the two lines below when done.
  echo "store_max_build() is not implemented — fill the TODO(project) block in scripts/release/release_upload.sh" >&2
  return 1
}
# store_upload PLATFORM N BUILD_NAME TRACK LISTING_FILE: build (if needed) and upload ONE platform. Exit 0 = the
#   binary is on the store with build number N. Must NOT release, promote, roll out or submit anything. Runs only in
#   mode=upload. BUILD_NAME is THAT platform's version name (platform_build_name), which is not always the same on
#   both stores. LISTING_FILE ('' or a JSON file) is the copy edited in the web UI — when given it wins over store/.
store_upload() {
  if [ -n "$SHIM" ]; then shim_store_upload "$@"; return $?; fi
  # TODO(project): e.g. an existing fastlane lane / gradle publish task / store CLI, with credentials read from
  #   "$SECRETS_DIR". Use $1 (ios|android), $2 (build number), $3 (version name), $4 (android track), and $5 —
  #   when not empty, the JSON file whose fields replace the store/ copy (writing it back into store/ is allowed).
  echo "store_upload() is not implemented — fill the TODO(project) block in scripts/release/release_upload.sh" >&2
  return 1
}

# ── selftest shims ───────────────────────────────────────────────────────────────────────────────────
shim_store_max_build() {
  echo "store_max_build" >>"$SHIM_CALLS"
  case "$SHIM" in poison) echo "18l";; *) echo "$SHIM_MAX";; esac
}
shim_store_upload() {
  echo "store_upload $1 $2 $3 $4 ${5:-}" >>"$SHIM_CALLS"
  case "$SHIM" in
    partial) [ "$1" = ios ];;      # ios succeeds, android fails
    fail)    return 1;;
    *)       return 0;;
  esac
}

# ── contract plumbing ────────────────────────────────────────────────────────────────────────────────
step()     { echo "::rcm::step::$1"; }
step_end() { echo "::rcm::step-end::$1"; }
finish()   { echo "::rcm::summary::$1"; exit "$2"; }
# listing_file_lines FILE: the fields of the edited copy (listing_json), one `<platform>.<key>: <value>` line each
#   (logged so the job says what went up with the binary).
listing_file_lines() {
  python3 - "$1" <<'PYEOF'
import json, sys
d = json.load(open(sys.argv[1], encoding="utf-8"))
for plat in ("ios", "android"):
    fields = d.get(plat) or {}
    if not isinstance(fields, dict):
        continue
    for key, value in fields.items():
        if isinstance(value, str):
            print(f"{plat}.{key}: {' '.join(value.split())}")
        elif isinstance(value, list):
            print(f"{plat}.{key}: {len(value)} file(s)")
PYEOF
}
# read_listing_json: RCM_INPUT_LISTING_JSON (the copy edited in the web UI) -> $WORK/listing.json + LISTING_FILE.
#   Empty = nothing edited, the store/ files are the copy. Not a JSON object = usage error (exit 2).
read_listing_json() {
  LISTING_FILE=""
  [ -n "${RCM_INPUT_LISTING_JSON:-}" ] || return 0
  if ! printf '%s' "$RCM_INPUT_LISTING_JSON" | python3 -c 'import json,sys; d=json.load(sys.stdin); assert isinstance(d, dict)' 2>/dev/null; then
    echo "RCM_INPUT_LISTING_JSON must be a JSON object ({\"ios\": {...}, \"android\": {...}})" >&2; usage
  fi
  printf '%s\n' "$RCM_INPUT_LISTING_JSON" >"$WORK/listing.json"; LISTING_FILE="$WORK/listing.json"
  echo "  listing_json given — $WORK/listing.json overrides the store/ copy"
}
write_upload() {  # $1 n(int|null) · $2 status · $3 mode · $4 tag(or '') · rest: uploaded platforms
  local n="$1" status="$2" mode="$3" tag="$4"; shift 4
  local args=(write upload --out "$OUT" --n "$n" --status "$status" --mode "$mode" --extra-json "{\"exit_code\": ${EXIT_CODE:-null}}")
  [ -n "$tag" ] && args+=(--tag "$tag")
  local p; for p in "$@"; do args+=(--platform "$p"); done
  python3 "$CONTRACT" "${args[@]}" && WRITTEN=1
}
on_exit() {  # 마지막 안전망 — 어떤 경로로 끝나든 upload.json 이 남는다
  local rc=$?
  [ "$WRITTEN" = 1 ] && return 0
  [ -n "${RCM_INPUT_BUILD_NAME:-}" ] || return 0
  local mode="${RCM_INPUT_MODE:-rehearsal}" status=failed
  [ "$mode" = rehearsal ] && status=rehearsal
  EXIT_CODE=$rc write_upload null "$status" "$mode" "" >/dev/null 2>&1 || true
}
trap on_exit EXIT

main() {
  local mode="${RCM_INPUT_MODE:-rehearsal}" bn="${RCM_INPUT_BUILD_NAME:-}" confirm="${RCM_INPUT_CONFIRM_BUILD_NUMBER:-}"
  local platform="${RCM_INPUT_PLATFORM:-both}" track="${RCM_INPUT_ANDROID_TRACK:-production}"
  local bna="${RCM_INPUT_BUILD_NAME_ANDROID:-}" shown
  local plats max expected plan_n p uploaded=() failed=() status rc
  case "$mode" in rehearsal|upload) ;; *) echo "RCM_INPUT_MODE must be rehearsal|upload, got '$mode'" >&2; usage;; esac
  case "$platform" in both) plats="ios android";; ios|android) plats="$platform";; *) echo "RCM_INPUT_PLATFORM must be both|ios|android, got '$platform'" >&2; usage;; esac
  case "$track" in production|internal) ;; *) echo "RCM_INPUT_ANDROID_TRACK must be production|internal, got '$track'" >&2; usage;; esac
  [[ "$bn" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "RCM_INPUT_BUILD_NAME must be X.Y.Z, got '$bn'" >&2; usage; }
  # 두 스토어 이름이 다를 때만 온다 — 비어 있으면 둘 다 $bn 이다(계약 §2 「Two store version names」).
  [[ "$bna" =~ ^([0-9]+\.[0-9]+\.[0-9]+)?$ ]] || { echo "RCM_INPUT_BUILD_NAME_ANDROID must be X.Y.Z or empty, got '$bna'" >&2; usage; }
  shown="$bn"; if [ -n "$bna" ] && [ "$bna" != "$bn" ]; then shown="$bn+$bna"; fi
  if [ "$mode" = upload ]; then
    # 사람이 이 제출에서 친 숫자만 받는다. 기본값·기억값·플래그로 대신할 수 없다.
    [[ "$confirm" =~ ^[0-9]+$ ]] || { echo "mode=upload needs RCM_INPUT_CONFIRM_BUILD_NUMBER — the N a human typed (plan.json n)" >&2; usage; }
  fi
  [ -f "$CONTRACT" ] || { echo "missing $CONTRACT — reinstall with /rcm-store-connect" >&2; exit 2; }
  mkdir -p "$WORK"
  read_listing_json
  [ -z "$LISTING_FILE" ] || listing_file_lines "$LISTING_FILE" | sed 's/^/  listing: /'
  echo "::rcm::steps::$((2 + $(echo "$plats" | wc -w) + 1))"

  step "preflight"
  if [ -z "$SECRETS_DIR" ] || [ ! -d "$SECRETS_DIR" ]; then
    step_end fail
    EXIT_CODE=2 write_upload null "$([ "$mode" = rehearsal ] && echo rehearsal || echo failed)" "$mode" ""
    finish "BLOCKED(env) — secrets folder missing (\$$SECRETS_ENV)" 2
  fi
  # TODO(project): tool checks (store CLI, signing tools). Missing -> same shape as above, exit 2.
  step_end ok

  step "store check"
  if ! max="$(store_max_build)" || ! [[ "$max" =~ ^[0-9]+$ ]]; then
    step_end fail
    EXIT_CODE=1 write_upload null "$([ "$mode" = rehearsal ] && echo rehearsal || echo failed)" "$mode" ""
    finish "failed — store_max_build() gave '${max:-}' (not an integer); nothing uploaded" 1
  fi
  expected=$((max + 1))
  # 드리프트: plan.json 이 있고 그때의 N 이 지금 스토어와 어긋나면 4 — 다시 plan 을 돌려야 한다.
  if [ -f "$WORK/plan.json" ]; then
    plan_n="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("n"))' "$WORK/plan.json" 2>/dev/null || echo None)"
    if [ "$plan_n" != None ] && [ "$plan_n" != "$expected" ]; then
      step_end fail
      EXIT_CODE=4 write_upload "$expected" "$([ "$mode" = rehearsal ] && echo rehearsal || echo failed)" "$mode" ""
      finish "store drift — plan said N=$plan_n, store now implies N=$expected. Re-run plan (exit 4)" 4
    fi
  fi
  # 확인 불일치: rehearsal 에서도 숫자를 줬다면 검사한다(리허설은 진짜의 예행이다).
  if [ -n "$confirm" ] && [ "$confirm" != "$expected" ]; then
    step_end fail
    EXIT_CODE=3 write_upload "$expected" "$([ "$mode" = rehearsal ] && echo rehearsal || echo failed)" "$mode" ""
    finish "confirmation mismatch — typed $confirm, store implies N=$expected (exit 3)" 3
  fi
  step_end ok

  if [ "$mode" = rehearsal ]; then
    for p in $plats; do step "rehearsal $p"; echo "  would upload $p $(platform_build_name "$p") ($expected) track=$track — rehearsal, no store call"; step_end ok; done
    step "upload.json"
    EXIT_CODE=0 write_upload "$expected" rehearsal rehearsal ""
    step_end ok
    finish "rehearsal ok — $shown N=$expected, nothing uploaded" 0
  fi

  for p in $plats; do
    step "upload $p"
    if store_upload "$p" "$expected" "$(platform_build_name "$p")" "$track" "$LISTING_FILE"; then uploaded+=("$p"); step_end ok; else failed+=("$p"); step_end fail; fi
  done
  step "upload.json"
  if [ "${#failed[@]}" = 0 ]; then status=success; rc=0
  elif [ "${#uploaded[@]}" = 0 ]; then status=failed; rc=1
  else status=partial; rc=1; fi
  # tag: the release tag is cut by the driver / a human after upload, so the skeleton reports null.
  # TODO(project): print the tag here if your upload step creates it (profile.tag pattern, e.g. prod/X.Y.Z-N).
  EXIT_CODE=$rc write_upload "$expected" "$status" upload "" ${uploaded[@]+"${uploaded[@]}"}
  step_end ok
  case "$status" in
    success) finish "uploaded — $shown N=$expected ${uploaded[*]-} (no release, no rollout: those are human steps)" 0;;
    partial) finish "partial — uploaded ${uploaded[*]-}, failed ${failed[*]-} (exit 1)" 1;;
    *)       finish "failed — nothing uploaded (${failed[*]-})" 1;;
  esac
}

# ── selftest ─────────────────────────────────────────────────────────────────────────────────────────
selftest() {
  local t rc fails=0
  t="$(mktemp -d)"; mkdir -p "$t/secrets"
  check() {  # $1 label · $2 expected rc · $3 actual · $4 assertion on upload.json ('' = skip) · $5 expected upload-call count
    if [ "$2" != "$3" ]; then echo "FAIL $1: exit $3, expected $2"; cat "$t/out"; fails=$((fails+1)); return; fi
    if [ -n "$4" ] && ! python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert $4, d" "$t/work/upload.json"; then
      echo "FAIL $1: upload.json assertion failed: $4"; fails=$((fails+1)); return
    fi
    local calls; calls="$(grep -c '^store_upload' "$t/calls" 2>/dev/null || true)"; calls="${calls:-0}"
    if [ "$5" != "$calls" ]; then echo "FAIL $1: store_upload called $calls times, expected $5"; fails=$((fails+1)); return; fi
    echo "  ok  $1"
  }
  run() {  # $1 shim · $2 keep plan.json? (plan n) · rest env
    local shim="$1" plan_n="$2"; shift 2
    rm -rf "$t/work" "$t/calls"; mkdir -p "$t/work"; rc=0
    [ -n "$plan_n" ] && python3 "$CONTRACT" write plan --out "$t/work/plan.json" --build-name 1.0.1 --n "$plan_n" >/dev/null
    env RELEASE_SHIM="$shim" RELEASE_SHIM_CALLS="$t/calls" RELEASE_WORK="$t/work" \
        "$SECRETS_ENV=$t/secrets" RCM_INPUT_BUILD_NAME=1.0.1 "$@" bash "$SELF" >"$t/out" 2>&1 || rc=$?
  }
  echo "[release_upload] selftest ($SECRETS_ENV)"
  run ok "";                                   check "no mode -> rehearsal, no upload call" 0 "$rc" "d['mode']=='rehearsal' and d['status']=='rehearsal' and d['n']==181" 0
  run ok "" RCM_INPUT_MODE=upload;             check "upload without typed N -> exit 2, no upload call" 2 "$rc" "d['status']=='failed' and d['n'] is None" 0
  run ok "" RCM_INPUT_MODE=upload RCM_INPUT_CONFIRM_BUILD_NUMBER=181
                                               check "upload with typed N=181 -> success both" 0 "$rc" "d['status']=='success' and d['platforms']==['ios','android'] and d['n']==181 and d['tag'] is None" 2
  grep -q 'store_upload android 181 1.0.1 production' "$t/calls" || { echo "FAIL track not passed"; fails=$((fails+1)); }
  run ok "" RCM_INPUT_MODE=upload RCM_INPUT_CONFIRM_BUILD_NUMBER=180
                                               check "typed 180 but store implies 181 -> exit 3, no upload call" 3 "$rc" "d['status']=='failed' and d['n']==181" 0
  run ok 175 RCM_INPUT_MODE=upload RCM_INPUT_CONFIRM_BUILD_NUMBER=176
                                               check "plan said 175, store now 181 -> drift exit 4" 4 "$rc" "d['n']==181" 0
  run partial "" RCM_INPUT_MODE=upload RCM_INPUT_CONFIRM_BUILD_NUMBER=181
                                               check "android fails -> partial exit 1" 1 "$rc" "d['status']=='partial' and d['platforms']==['ios']" 2
  run ok "" RCM_INPUT_MODE=upload RCM_INPUT_CONFIRM_BUILD_NUMBER=181 RCM_INPUT_PLATFORM=ios
                                               check "platform=ios uploads one" 0 "$rc" "d['platforms']==['ios']" 1
  run poison "" RCM_INPUT_MODE=upload RCM_INPUT_CONFIRM_BUILD_NUMBER=181
                                               check "poisoned store answer -> red exit 1, no upload call" 1 "$rc" "d['status']=='failed' and d['n'] is None" 0
  run ok "" RCM_INPUT_ANDROID_TRACK=beta;      check "unknown track -> usage exit 2" 2 "$rc" "d['status']=='rehearsal'" 0
  run ok "" "$SECRETS_ENV=$t/none";            check "no secrets dir -> exit 2, store untouched" 2 "$rc" "d['status']=='rehearsal' and d['n'] is None" 0
  [ ! -e "$t/calls" ] || { echo "FAIL store read without secrets"; fails=$((fails+1)); }
  # listing_json — the copy edited in the web UI: a file for the hook, its fields in the log
  run ok "" RCM_INPUT_LISTING_JSON='{"ios": {"subtitle": "X"}}'
                                               check "listing_json in rehearsal -> listing.json written, no upload call" 0 "$rc" "d['status']=='rehearsal'" 0
  python3 -c "import json,sys; d=json.load(open(sys.argv[1])); assert d['ios']['subtitle']=='X'" "$t/work/listing.json" || { echo "FAIL listing.json missing or wrong"; fails=$((fails+1)); }
  grep -q '^  listing: ios.subtitle: X$' "$t/out" || { echo "FAIL listing fields not logged"; fails=$((fails+1)); }
  run ok "" RCM_INPUT_LISTING_JSON='{"ios": {"subtitle": "X"}}' RCM_INPUT_MODE=upload RCM_INPUT_CONFIRM_BUILD_NUMBER=181 RCM_INPUT_PLATFORM=ios
                                               check "listing_json in upload -> path handed to store_upload" 0 "$rc" "d['status']=='success'" 1
  grep -q "^store_upload ios 181 1.0.1 production $t/work/listing.json\$" "$t/calls" || { echo "FAIL listing.json path not passed to store_upload"; cat "$t/calls"; fails=$((fails+1)); }
  run ok "" RCM_INPUT_LISTING_JSON='"text"';   check "listing_json not an object -> usage exit 2" 2 "$rc" "d['status']=='rehearsal'" 0
  run ok "";                                   check "no listing_json -> no listing.json" 0 "$rc" "d['status']=='rehearsal'" 0
  [ ! -e "$t/work/listing.json" ] || { echo "FAIL listing.json written without listing_json"; fails=$((fails+1)); }
  # 두 스토어 버전 이름 — 플랫폼마다 자기 이름이 훅으로 간다(계약 §2 「Two store version names」)
  run ok "" RCM_INPUT_MODE=upload RCM_INPUT_CONFIRM_BUILD_NUMBER=181 RCM_INPUT_BUILD_NAME=1.1.1 RCM_INPUT_BUILD_NAME_ANDROID=1.0.1
                                               check "two store names -> ios 1.1.1 · android 1.0.1" 0 "$rc" "d['status']=='success'" 2
  grep -q '^store_upload ios 181 1.1.1 production' "$t/calls" && grep -q '^store_upload android 181 1.0.1 production' "$t/calls" \
    || { echo "FAIL per-platform build name not handed to store_upload"; cat "$t/calls"; fails=$((fails+1)); }
  run ok "" RCM_INPUT_MODE=upload RCM_INPUT_CONFIRM_BUILD_NUMBER=181 RCM_INPUT_BUILD_NAME=1.1.1 RCM_INPUT_BUILD_NAME_ANDROID=
                                               check "empty build_name_android -> both stores get 1.1.1" 0 "$rc" "d['status']=='success'" 2
  grep -q '^store_upload android 181 1.1.1 production' "$t/calls" || { echo "FAIL android did not fall back to build_name"; cat "$t/calls"; fails=$((fails+1)); }
  run ok "" RCM_INPUT_BUILD_NAME_ANDROID=1.0;  check "build_name_android not X.Y.Z -> usage exit 2" 2 "$rc" "d['status']=='rehearsal'" 0
  rm -rf "$t"
  [ "$fails" = 0 ] && { echo "[release_upload] selftest PASS — rehearsal by default, typed N enforced, listing_json reaches the hook, each store gets its own name, poison goes red"; return 0; }
  echo "[release_upload] selftest FAIL ($fails)"; return 1
}

case "${1:-}" in --selftest) WRITTEN=1; selftest;; "") main;; *) usage;; esac
